### ISSUE TITLE
After TakePhotoAsync the app restarts or closes

### ISSUE THREAD

**Issue by georgethms10** [jamesmontemagno/MediaPlugin#301] opened 2017-07-18 12:21 UTC
When i use the library to take photo using samsung s7 s6 and motorolla x play it works fine, But when i try it with Samsung Galaxy A3 or Wiko Lenny 3 the app restarts or closes.
I tried to get stacktrace but its printing none

## Bug Information

Version Number of Plugin:  2.7.0.50beta
Device Tested On:  Samsung Galaxy A3 or Wiko Lenny 3
Simulator Tested On:
Version of VS: 2017 VS
Version of Xamarin forms: 2.3.4.247
Versions of other things you are using:
   using xam.plugin.media version 3.0.1 in shared project

### Steps to reproduce the Behavior
Try to take a photo using TakePhotoAsync app restarts
### Expected Behavior
It should get the corresponding picture
### Actual Behavior
App crash or restart
### Code snippet

`             async Task TakePhoto()
		{
			if (!(CrossMedia.Current.IsCameraAvailable) || !
                                 (CrossMedia.Current.IsTakePhotoSupported))
			{
				await DisplayAlert(Localize.GetString("res_cand_alert", ""), 
                                 Localize.GetString("res_cand_nocam1", ""), Localize.GetString("res_cand_ok", 
                                 ""));
				return;
			}
			diploma = await CrossMedia.Current.TakePhotoAsync(new 
                                                                                    StoreCameraMediaOptions
			{

				DefaultCamera = CameraDevice.Rear,
				Directory = "sample",
				Name = Utilities.Constants.cvImageName + Utilities.Constants.JPEGExt,
                               PhotoSize = PhotoSize.Small
                                

			});

			if (diploma == null)
				return;
			else
			{
				AddPhoto(diploma);
			}
		}`

**Comment by jamesmontemagno** [comment] 2017-07-18 17:14
Duplicate of #286

**Closed by jamesmontemagno** 2017-07-18 17:14 UTC
