### ISSUE TITLE
Option file saved.

### ISSUE THREAD

**Issue by kingnguyen1993** [jamesmontemagno/MediaPlugin#387] opened 2017-11-03 02:58 UTC
There is any option to prevent image saved in 2 place?
I see that image has been saved in 2 place, 1 at Pictures and 1 at software folder.

**Comment by prashantvc** [comment] 2017-11-03 07:27
Did you set the `SaveToAlbum = false`? This will prevent from saving image in two places
Also, this looks a duplicate of issue #89

**Comment by kingnguyen1993** [comment] 2017-11-03 08:12
Yes, I've just set SaveToAlbum = false, and It's still save in two place. I use LG G2, Android 4.4.2 to tesst.

**Comment by jamesmontemagno** [comment] 2017-11-03 13:48
Duplicate: https://github.com/jamesmontemagno/MediaPlugin/issues/89

**Closed by jamesmontemagno** 2017-11-03 13:48 UTC
Labels: in-review, need-more-info
