### ISSUE TITLE
[Feature Request] When using TakeVideoAsync it does not implement StoreVideoOptions.

### ISSUE THREAD

**Issue by ChrisMacLeanRQI** [jamesmontemagno/MediaPlugin#178] opened 2017-02-15 17:36 UTC
## Bug 
When recording a video we set the StoreVideoOptions, but they are not implemented.  The TakePhotoAsync() works great.  We are able to save to a custom Directory with a unique Name. 

Code for TakePhotoAsync():
var photofile = await CrossMedia.Current.TakePhotoAsync(new Plugin.Media.Abstractions.StoreCameraMediaOptions { Directory = "Pictures", Name = "filename.jpg" });

Result is ../LocalState/Pictures/filename.jpg

Code for TakeVideoAsync():
var videofile = await CrossMedia.Current.TakeVideoAsync(new Plugin.Media.Astractions.StoreVideoOptions { Directory = "Videos", Name = "filename.mp4" });

Result is ../TempState/CCapture.mp4

Version Number of Plugin: v2.6.2
Device Tested On: Lumia 950 XL
Simulator Tested On: Visual Studio UWP and Android Emulators

### Expected Behavior
Ability to set Directory and Name of video file using StoreVideoOptions.

### Actual Behavior
The default values are being implemented.  No directory is created and the file name is CCapture.mp4

**Comment by daniel-packard** [comment] 2017-12-22 20:32
Hi @jamesmontemagno - I'm happy to contribute a fix for UWP in the next couple days 👌

**Comment by jamesmontemagno** [comment] 2017-12-22 20:36
I think @prashantvc maybe was working on it? Maybe not?

**Comment by daniel-packard** [comment] 2017-12-22 21:18
Ahhh, I just saw the `up-for-grabs` label was added a couple days ago, but now I see it was added _and_ removed.

@prashantvc -- let me know if you have a fix in the works, otherwise I'd be happy to make a contribution.

**Comment by daniel-packard** [comment] 2017-12-22 21:34
PS -- seems this duplicates https://github.com/jamesmontemagno/MediaPlugin/issues/308

**Comment by jamesmontemagno** [comment] 2017-12-22 21:56
I think there are a few branches where he started work. Probably need some guidance there.

**Comment by daniel-packard** [comment] 2017-12-22 22:43
Hmmm... tell you what, those issue-308 branches look a little bigger scope than the tiny fix I'd like to get in... I'll open a PR against master and request @prashantvc 's review to see what he thinks.

thanks!

**Comment by prashantvc** [comment] 2017-12-26 13:00
re: https://github.com/jamesmontemagno/MediaPlugin/issues/178#issuecomment-353676083

Fix for this should be available in the [issue-308] (https://github.com/jamesmontemagno/MediaPlugin/tree/issue-308) branch. Changes in your PR will work too, but they are not ready for `master` branch yet

**Closed by prashantvc** 2017-12-26 13:00 UTC
Labels: feature, triaged, up-for-grabs

**Comment by jcmontoya** [comment] 2020-01-26 03:21
I am using version 4.0.1.5 and the issue is still happening. 

The default values are ignored. No directory is created and the file name is CCapture.mp4
