### ISSUE TITLE
[Feature Request] Ability to specify the directory that "PickPhotos" are copied to

### ISSUE THREAD

**Issue by CrimsonKyle** [jamesmontemagno/MediaPlugin#63] opened 2016-08-30 22:26 UTC
## Feature Request:

_Current State:_
"PickPhotos" currently allows you to pick photos from the gallary or camera roll which then gets written to a temp directory that looks similar to (var/mobile/Containers/Data/Applications/{App Identifier}/Documents/temp/{name of picture}.{extension})

_Problem:_ 
Files in a system-designated temporary directory make no guarantees about how long they’ll exist before being deleted automatically by the operating system. In other words that photo you just wrote to the temp directory can be cleaned up and disappear without any warning.  So if you are referencing that image's path location in your application it will no longer render an image.

![so-if-you-hhaao3](https://cloud.githubusercontent.com/assets/16037523/18109549/9bf0e168-6ed7-11e6-98b8-1ab71a281dbd.jpg)

_Solution:_
When you "PickPhotos", and you want the image you are selecting to hang around "long term" or at least until you choose to delete it, be able to set a directory in which the photo is copied to for long term reference.

**Comment by CrimsonKyle** [comment] 2016-08-31 15:39
This is a workaround I now have working for this issue.

```
 public static async Task<MediaFile> ChoosePhoto(string directory = "{insert default album name}")
 {
			await CrossMedia.Current.Initialize();

            //Check Permissions
			if (!CrossMedia.Current.IsCameraAvailable || !CrossMedia.Current.IsTakePhotoSupported)
				throw new Exception ("Unable to access Photos");
            //Pick Photo
			MediaFile file = await CrossMedia.Current.PickPhotoAsync();

            //Get Root Documents Directory And Add Variable Directory
			string folderPath = System.Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments);
			folderPath = Path.Combine(folderPath, directory);

            //If Variable Directory Does Not Exist Create It
			if (!System.IO.File.Exists(folderPath))
				Directory.CreateDirectory(folderPath);

	    //Create New File Path
			var newPath = System.IO.Path.Combine(folderPath, 
			                                     Path.GetFileNameWithoutExtension(file.Path) + System.IO.Path.GetExtension(file.Path));

	   //If New File Path Exists Delete It	
			if (System.IO.File.Exists(newPath))
				System.IO.File.Delete(newPath);

	    //Copy File to New File Path
			File.Copy(file.Path, newPath);

           //Return New Media File
			return new MediaFile(newPath,file.GetStream);
 }
```

**Comment by vinguan** [comment] 2017-03-04 11:54
I  am facing the same problem. Coping from Temp folder to Pictures folder and delete after will be a unnecessary overhead. if we can choose where the photos picked from gallery are copied to, that would be great.

**Comment by ericbrunner** [comment] 2017-03-13 10:50
It should be sufficient to specify your own custom directory in PickMediaOptions.Directory . Create an instance and pass it to the PickPhotoAsync as an actual argument. But be sure to delete the file by yourself when you don't need it any more with File.Delete(takenphotopath) in your plattform specific (iOS, Android, ...) projects. I use that approach to store the path in a Photo Upload Queue for later transfer when I have to upload photos and app is in airplain mode.

**Comment by jamesmontemagno** [comment] 2017-08-31 00:41
I think this is a duplicate of #20 ....

**Comment by devology-rob** [comment] 2017-10-04 09:14
Hey @jamesmontemagno I twetted you yesterday to discuss an issue.  

This sounds like the issue I'm looking at - I noticed some of our photo paths included the /temp folder which concerned me on how long-living the photo would be.  I want to keep them in an application folder until I **explicitly** delete them.

@CrimsonKyle I'll attempt your workaround in the meantime, but is this line the correct path for iOS **and** Android (and in the future Windows UWP when I get around to implementing that version).

string folderPath = System.Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments);

Thanks all,
Rob.

**Comment by devology-rob** [comment] 2017-10-04 10:49
I adapted the code at https://gist.github.com/Adam-- to copy the file (I'm using the PCLStorage plugin that doesn't expose a copy file method)...

```
using System;
namespace VehicleSmart.Services
{
    using System.Threading;
    using System.Threading.Tasks;
    using PCLStorage;
    using FileAccess = PCLStorage.FileAccess;

    public static class PCLStorageExtensions
    {
        public static async Task<IFile> CopyFileTo(this IFile file, IFolder destinationFolder, CancellationToken cancellationToken = default(CancellationToken))
        {
            var destinationFile =
                await destinationFolder.CreateFileAsync(file.Name, CreationCollisionOption.ReplaceExisting, cancellationToken);

            using (var outFileStream = await destinationFile.OpenAsync(FileAccess.ReadAndWrite, cancellationToken))
            using (var sourceStream = await file.OpenAsync(FileAccess.Read, cancellationToken))
            {
                await sourceStream.CopyToAsync(outFileStream, 81920, cancellationToken);
            }

            return destinationFile;
        }
    }
}

```

Here's how I've implemented it

```
        private static async Task<PhotoResult> TakePhotoFromDevice(bool takePhoto, VehicleDataModel vdm, int maxWidth, ILogger logger)
		{
            var targetFilename = vdm.VehicleDetails.Registration + (DateTime.UtcNow.Ticks / TimeSpan.TicksPerSecond)+".jpg";
			var photoResult = new PhotoResult();

			await CrossMedia.Current.Initialize();

            if ((takePhoto && !CrossMedia.Current.IsCameraAvailable || !CrossMedia.Current.IsTakePhotoSupported) ||
               (!takePhoto && !CrossMedia.Current.IsPickPhotoSupported))
			{
                ...
                photoResult.Success = false;
            } else {

				var file = takePhoto ? await CrossMedia.Current.TakePhotoAsync(new Plugin.Media.Abstractions.StoreCameraMediaOptions
                {
                    Directory = "Vehicle Smart",
                    Name = targetFilename,
                    MaxWidthHeight = maxWidth,
                    PhotoSize = PhotoSize.MaxWidthHeight,
					CompressionQuality = 92,
                    SaveToAlbum = true
				}) : await CrossMedia.Current.PickPhotoAsync(new Plugin.Media.Abstractions.PickMediaOptions
				{
					MaxWidthHeight = maxWidth,
                    PhotoSize = PhotoSize.MaxWidthHeight,
					CompressionQuality = 92                  
				});

                if (file == null)
                {
					photoResult.Success = false;
                    photoResult.ErrorMessage = "User canceled";
                }
                else
                {
                    // The photos taken by the Media Plugin appear to be dumped
                    // into a temp folder (esp photo reel), so we want to move them into an
                    // application folder that we control instead.
                    IFolder targetFolder = null;

                    try
                    {
						targetFolder = await FileSystem.Current.LocalStorage.CreateFolderAsync("vehiclesmartphotos", CreationCollisionOption.FailIfExists);
                    } catch (Exception e) {
                        ...
					}

					targetFolder = await FileSystem.Current.LocalStorage.GetFolderAsync("vehiclesmartphotos");
                    if (targetFolder == null)
                    {
						photoResult.Success = false;
                        photoResult.ErrorMessage = "Unable to store photo, please check your permissions";
                    }
                    else
                    {
						//Copy File to New File Path
						var existingFile = await FileSystem.Current.GetFileFromPathAsync(file.Path);
						var newFile = await existingFile.CopyFileTo(targetFolder);

                        // Delete old temp file
                        await existingFile.DeleteAsync();

                        photoResult.Success = true;
                        photoResult.ImagePath = newFile.Path;
                    }


				}
			}

			return photoResult;
		}

```

**Comment by jamesmontemagno** [comment] 2019-11-13 00:49
No new features.

**Closed by jamesmontemagno** 2019-11-13 00:49 UTC
Labels: feature, up-for-grabs
