### ISSUE TITLE
Android app crashes and navigation go to Home page

### ISSUE THREAD

**Issue by mbassi** [jamesmontemagno/MediaPlugin#344] opened 2017-09-18 19:46 UTC
If you are creating an issue for a BUG please fill out this information. If you are asking a question or requesting a feature you can delete the sections below. 

**Failure to fill out this information will result in this issue being closed.** If you post a full stack trace in a bug it will be closed, please post it to http://gist.github.com and then post the link here.

## Bug Information

Version Number of Plugin:2.6.2
Device Tested On: Samsung Galaxy J5
Simulator Tested On: Kitkat 4.4
Version of VS: 2017
Version of Xamarin: 4.4.0.34
Versions of other things you are using:

### Steps to reproduce the Behavior
Waits til timer opens the camera
Take the picture
App crashes and HomePage is opened

### Expected Behavior
Open the last opened page after closing the camera

### Actual Behavior
It crashes the app and homepage is opened

### Code snippet

<details>
<summary>Starts Content Page Code</summary>

```
private PhotoTimer photoNotifyTimer;
public DistribuicaoPage()
{
	photoNotifyTimer = new PhotoTimer(App.TempoFoto);
    photoNotifyTimer.CodigoDistribuicao = App.DistribuicaoCodigo;
}

protected  override void OnAppearing()
{
	lblDistribuindo.Text = "DISTRIBUINDO";
	Task photoTask = Task.Factory.StartNew(async() => await photoNotifyTimer.Start());
	
}

//Ends  Content Page Code
//Start photo timer code
using Newtonsoft.Json;
using Plugin.Media;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Xamarin.Forms;

namespace TrackLaser
{
    public class PhotoTimer
    {
        public INavigation Navigation { get; set; }
        public String CodigoDistribuicao { get; set; }
        private int _waitTime;
        private TakePhotoError _photoReturnError;
        private int evento =0;
        
        
        public TakePhotoError PhotoReturnError
        {
            get
            {
                return this._photoReturnError;
            }
            set
            {
                this._photoReturnError = value;
            }
        }
        public int WaitTime
        {
            get { return _waitTime; }
            set { _waitTime = value; }
        }

        private bool _isRunning;
        public bool IsRunning
        {
            get { return _isRunning; }
            set { _isRunning = value; }
        }
    
        public PhotoTimer(int waitTime)
        {
            WaitTime = waitTime;
        }
        
        public async Task Start()
        {
            int seconds = 0;
            IsRunning = true;
            while (IsRunning)
            {
                if (seconds != 0 && seconds % WaitTime == 0)
                {
                    await TakePhoto();
                   
                }
                await Task.Delay(1000);
                seconds++;
            }
        }

        public void Stop()
        {
            IsRunning = false;
        }
        public String ConcatenaData(String mensagem)
        {
            /*
            String retorno = DateTime.Now.ToString("dd/MM/yyyy HH:mm:ss");
            */
            String retorno = mensagem + " ";
            return retorno;
        }
        public async Task TakePhoto()
        {
            String logNotificationMessage = ConcatenaData("1");
            try
            {
                var log = DependencyService.Get<ILog>();

                var audioPlayer = DependencyService.Get<IAudioPlayer>();
                logNotificationMessage += ConcatenaData("2");
                audioPlayer.Play();
                logNotificationMessage += ConcatenaData("3");
                await CrossMedia.Current.Initialize();
                logNotificationMessage += ConcatenaData("4");
                if (!CrossMedia.Current.IsCameraAvailable || !CrossMedia.Current.IsTakePhotoSupported)
                {

                    return;
                }
                logNotificationMessage += ConcatenaData("5");
                var file = await CrossMedia.Current.TakePhotoAsync(new Plugin.Media.Abstractions.StoreCameraMediaOptions
                {
                    Directory = "\\Imagens",
                    SaveToAlbum = false,
                    Name = Guid.NewGuid().ToString()

                });
                logNotificationMessage += ConcatenaData("6");
                if (file != null)
                {
                    this.evento++;
                    logNotificationMessage += ConcatenaData("7");
                    var restClient = DependencyService.Get<IRestClient>();
                    logNotificationMessage += ConcatenaData("8");
                    Error uploadError = restClient.UploadFileViaFTP(file.Path);
                    logNotificationMessage += ConcatenaData("9");
                    this._photoReturnError = new TakePhotoError();
                    this._photoReturnError.Uploaded = uploadError.Sucess;
                    this._photoReturnError.UploadMessage = uploadError.Message;
                    this._photoReturnError.UploadAditionaRespone = uploadError.AditionalResponse;
                    this._photoReturnError.SavedToServerDataBase = false;
                    this.PhotoReturnError.SaveToServerDataBaseMessage = "Falha no upload";
                    int ServerPhotoId = 0;
                    DateTime date = DateTime.Now;
                    DateTime? syncDate = null;
                    if (this._photoReturnError.Uploaded)
                    {
                        DateTime syncDateRemote = DateTime.Now;
                        SyncDatabaseModel remoteyncData = new SyncDatabaseModel();
                        remoteyncData.date = date;
                        remoteyncData.evento = this.evento;
                        remoteyncData.Id = ServerPhotoId;
                        remoteyncData.id_reg = this.CodigoDistribuicao;
                        remoteyncData.image = "/images/" + uploadError.Message;
                        remoteyncData.sync = true;
                        remoteyncData.syncdate = syncDateRemote;
                        remoteyncData.type = "PHOTO";
                        remoteyncData.way = "CS";
                        logNotificationMessage += ConcatenaData("10");
                        var json = JsonConvert.SerializeObject(remoteyncData);
                        logNotificationMessage += ConcatenaData("11");
                        Error postDataError = restClient.PostObject("data", json);
                        this._photoReturnError.SavedToServerDataBase = postDataError.Sucess;
                        this._photoReturnError.SaveToServerDataBaseMessage = postDataError.Message;
                        this._photoReturnError.SaveToServerDataBaseAditionaRespone = postDataError.AditionalResponse;

                        if (this._photoReturnError.SavedToServerDataBase)
                        {
                            String jsonPosted = this._photoReturnError.SaveToServerDataBaseMessage;
                            SyncDatabaseModel syncDataPosted = JsonConvert.DeserializeObject<SyncDatabaseModel>(jsonPosted);
                            ServerPhotoId = syncDataPosted.Id;
                            syncDate = syncDateRemote;
                        }

                    }
                    logNotificationMessage += ConcatenaData("12");
                    bool sync = (this._photoReturnError.Uploaded && _photoReturnError.SavedToServerDataBase);

                    SyncDatabaseModel localSyncData = new SyncDatabaseModel();
                    localSyncData.date = date;
                    localSyncData.evento = this.evento;
                    localSyncData.Id = ServerPhotoId;
                    localSyncData.id_reg = this.CodigoDistribuicao;
                    localSyncData.image = file.Path;
                    localSyncData.sync = sync;
                    localSyncData.syncdate = syncDate;
                    localSyncData.type = "PHOTO";
                    localSyncData.way = "CS";
                    logNotificationMessage += ConcatenaData("13");
                    AcessoDados dados = new AcessoDados();
                    logNotificationMessage += ConcatenaData("14");
                    Error localSaveError = dados.Insert(localSyncData);
                    logNotificationMessage += ConcatenaData("15");
                    this._photoReturnError.SavedToLocalDatabase = localSaveError.Sucess;
                    this._photoReturnError.SaveToLocalDatabaseAditionaRespone = localSaveError.AditionalResponse;
                    this._photoReturnError.SaveToLocalDatabaseMessage = localSaveError.Message;
                    String photoSyncResponse = String.Empty;
                    if (this._photoReturnError != null)
                    {
                        logNotificationMessage += ConcatenaData("16");
                        String notificationTite = "Foto enviada com sucesso!";
                        if (this._photoReturnError.SavedToLocalDatabase == false || this._photoReturnError.SavedToServerDataBase == false || this._photoReturnError.Uploaded == false)
                        {
                            notificationTite = "Ocorreram erros no envio da foto";
                        }
                        if (!this._photoReturnError.SavedToLocalDatabase)
                        {
                            photoSyncResponse += "Erro ao salvar no celular causa:" + this._photoReturnError.SaveToLocalDatabaseMessage + "\r\n" + this._photoReturnError.SaveToLocalDatabaseAditionaRespone;
                        }
                        else
                        {
                            photoSyncResponse += "Salvamento local bem sucedido";
                        }
                        if (!this._photoReturnError.SavedToServerDataBase)
                        {
                            photoSyncResponse += "\r\nErro ao sincronizar com o servidor causa:" + this._photoReturnError.SaveToServerDataBaseMessage + "\r\n" + this._photoReturnError.SaveToServerDataBaseAditionaRespone;
                        }
                        else
                        {
                            photoSyncResponse += "\r\nSalvamento no server bem sucedido";
                        }
                        if (this._photoReturnError.Uploaded == false)
                        {
                            photoSyncResponse += "\r\nErro ao transferir o arquivo da foto causa: " + this._photoReturnError.UploadMessage + "\r\n" + this._photoReturnError.UploadAditionaRespone;
                        }
                        else
                        {
                            photoSyncResponse += "\r\nUpload bem sucedido";
                        }
                        logNotificationMessage += ConcatenaData("17");
                        var appNotification = DependencyService.Get<INotification>();
                        logNotificationMessage += ConcatenaData("18");
                        try
                        {
                            appNotification.SendNotification(notificationTite, photoSyncResponse, "Resultado do envio da foto",0);
                            logNotificationMessage += ConcatenaData("19");
                        }
                        catch
                        {

                        }



                    }
                    /*
                    var emailObject = DependencyService.Get<IEmail>();
                    emailObject.SendEmail("marcelo.bassi@gmail.com", "Artlaser", "Tratamento do erro da tirada da photo", photoSyncResponse);
                    */


                    /*
                    imgTirada.Source = ImageSource.FromStream(() => file.GetStream());
                    imgTirada.IsVisible = true;
                    */

                }
            }
            catch(Exception ex)
            {
                logNotificationMessage += ConcatenaData("\r\nErro no envio de foto: " + ex.Message);
            }
            finally
            {
                logNotificationMessage += ConcatenaData("20");
                var appNotificationLog = DependencyService.Get<INotification>();
                try
                {
                    appNotificationLog.SendNotification("Log do envio da foto " + DateTime.Now.ToString("dd/MM/yyyy HH:mm:ss"), logNotificationMessage, "Log do envio da foto",1);
                }
                catch
                {

                }
            }
            
        }
    }
}
```
<details>
// end phototimer code

**Comment by prashantvc** [comment] 2017-09-19 08:14
Could you share a sample project adding just the code to demonstrate this issue? It will help us to prioritise, and fix the issue

**Comment by jamesmontemagno** [comment] 2017-09-20 00:08
Do you have kill activities on in your developer settings?

**Comment by mbassi** [comment] 2017-09-20 12:41
await CrossMedia.Current.Initialize();

                if (!CrossMedia.Current.IsCameraAvailable ||
!CrossMedia.Current.IsTakePhotoSupported)
                {

                    return;
                }

                var file = await CrossMedia.Current.TakePhotoAsync(new
Plugin.Media.Abstractions.StoreCameraMediaOptions
                {
                    Directory = "\\Imagens",
                    SaveToAlbum = false,
                    Name = Guid.NewGuid().ToString()

                });

**Comment by mbassi** [comment] 2017-09-20 12:41
I don't know about developer setting

**Comment by jamesmontemagno** [comment] 2017-09-20 16:18
try to simplify your code. looking at your sample you are running things on other threads and timers. you need to invoke on the UI thread.

**Comment by jamesmontemagno** [comment] 2017-10-29 20:43
Duplicate of https://github.com/jamesmontemagno/MediaPlugin/issues/286 most likely, closing

**Closed by jamesmontemagno** 2017-10-29 20:43 UTC
Labels: bug, triaged
