### ISSUE TITLE
With 3.0.1 the image from the camera, on iOS, is always rotated.

### ISSUE THREAD

**Issue by zippo227** [jamesmontemagno/MediaPlugin#323] opened 2017-08-17 04:02 UTC
## Bug Information

Version Number of Plugin:3.0.1
Device Tested On:iPhone 6 Plus
Simulator Tested On:Unavailable
Version of VS: 7.1 BUild 1297
Version of Xamarin:Xamarin.iOS
Version: 10.12.0.18
Versions of other things you are using:uhhh

### Steps to reproduce the Behavior
pass StoreCameraMediaOptions to CrossMedia.Current.TakePhotoAsync. Take a picture with your camera

### Expected Behavior
Image is in same orientation as when you took the photo

### Actual Behavior
image is rotated to 90 degrees clockwise
### Code snippet
var mediaOptions = new StoreCameraMediaOptions
{
	Directory = dir,
	Name = redacted,
	AllowCropping = true,
	PhotoSize = PhotoSize.Full,
	SaveToAlbum = true,
	RotateImage = false
};

var localFile = await CrossMedia.Current.TakePhotoAsync(mediaOptions);
### Screenshots
![img_6109](https://user-images.githubusercontent.com/1617031/29395527-f4ff196e-82d6-11e7-80fc-9231b63e1bb6.PNG)
![img_6111](https://user-images.githubusercontent.com/1617031/29395528-f6e63fa0-82d6-11e7-8ae5-d286886e6b04.PNG)

**Comment by zippo227** [comment] 2017-08-17 04:08
The value should also not default to true. People who update the package and don't test, uh who would do that (me), will all the sudden have all their images roated when they show it off.

**Comment by jamesmontemagno** [comment] 2017-08-17 16:27
Duplicate of #304

**Closed by jamesmontemagno** 2017-08-17 16:27 UTC
