### ISSUE TITLE
StoreCameraMediaOptions ignored on UWP

### ISSUE THREAD

**Issue by solomonfried** [jamesmontemagno/MediaPlugin#774] opened 2019-11-27 04:10 UTC
## Bug Information

Version Number of Plugin: Xam.Plugin.Media 4.4.8 beta
Device Tested On: Windows Surface Tablet
Simulator Tested On:
Version of VS: 2019
Version of Xamarin:4.3.0.99
Versions of other things you are using:

### Steps to reproduce the Behavior
Create media options as 
  var mediaOptions = new StoreCameraMediaOptions()
            {
                SaveMetaData = false,
                Directory = "ContactPics",
                Name = "csImage.jpg",
                AllowCropping = false
            };

 var file = await CrossMedia.Current.TakePhotoAsync(mediaOptions);

### Expected Behavior
file should contain a ContactPics directory and the file name should be csImage.jpg

### Actual Behavior
File is being save in user/AppData/Local/Packages/{APP DIRECTORY}/LocalCache/CCapture (n).jpg

### Code snippet
See above
### Screenshots
NA

**Comment by TTalpey** [comment] 2019-12-06 16:13
This appears to be a duplicate of issue #705, which is still open since July btw.

**Closed** 2022-02-04 01:05 UTC
