### ISSUE TITLE
PickVideoAsync throws System.UnauthorizedAccessException

### ISSUE THREAD

**Issue by aleksandrsmyk** [jamesmontemagno/MediaPlugin#770] opened 2019-11-04 19:32 UTC
PickVideoAsync stops working.
To reproduce an issue we can use the sample solution in the current repo. Just call PickVideoAsync method and the then tap "Select" button, after compressing of an video, System.UnauthorizedAccessException will be thrown:

Access to the path '/private/var/mobile/Containers/Data/PluginKitPlugin/931B6D61-7D2F-498D-8EA0-3A3DB5349A86/tmp/trim.DCD06055-FBC9-42B6-9D63-847FD7EA463E.MOV' is denied

**Comment by jhylmb** [comment] 2019-11-06 13:03
Same issue here. 

In iOS 13, saving path of compressed video seems to be changed and I think that is the cause of this issue.

![image](https://user-images.githubusercontent.com/25781633/68299436-08965b80-00df-11ea-802c-1988065cb3fe.png)
In iOS 13.1.3 of physical iphone6s, after compressing iOS tries to save the video to '..../Containers/Data/PluginKitPlugin/...' and we have no permission to access the path.

![image](https://user-images.githubusercontent.com/25781633/68299321-cec55500-00de-11ea-87cc-55f6e1c2adb0.png)
In iOS 12.4 of iphone 8 simulator, it saves the video to '.../Containers/data/Application/...' and no problem.

**Comment by akatsukle** [comment] 2019-11-12 07:47
This looks like a duplicate of #739

**Comment by jhylmb** [comment] 2019-11-12 14:14
> This looks like a duplicate of #739

That's true. 4.4.6-beta fix this issue

**Closed** 2019-11-12 21:24 UTC

**Comment by raliqala** [comment] 2024-05-20 13:08
This is happening on android now
