### ISSUE TITLE
[iOS] Camera/Photo gallery does not show when calling on PickPhotoAsync or TakePhotoAsync 

### ISSUE THREAD

**Issue by Cyqlblgy** [jamesmontemagno/MediaPlugin#266] opened 2017-06-07 02:22 UTC
If you are creating an issue for a BUG please fill out this information. If you are asking a question or requesting a feature you can delete the sections below. 

**Failure to fill out this information will result in this issue being closed.** If you post a full stack trace in a bug it will be closed, please post it to http://gist.github.com and then post the link here.

## Bug Information

Version Number of Plugin:2.6.2
Device Tested On:iPod Touch 5th Generation with 9.3.5/iPhone 6 with 10.2.1
Simulator Tested On: None
Version of VS: 7.0.1(build 24)
Version of Xamarin:
Versions of other things you are using: Mono Version 5.0.1.1 & Version 4.8.1

### Steps to reproduce the Behavior
Calling PickPhotoAsync or TakePhotoAsync after actionSheet selection
### Expected Behavior
Take picture or pick photo 
### Actual Behavior
App is still responsive but no photo gallery/camera shows up 
### Code snippet
await CrossMedia.Current.Initialize();
				//logoImage.Dispose();
				var action = await DisplayActionSheet("Please pick your photo source", "Cancel", null, "Take picture","Photo gallery");
				if (action.Equals("Photo gallery"))
				{
					var photoStatus = await CrossPermissions.Current.CheckPermissionStatusAsync(Permission.Photos);
					var storageStatus = await CrossPermissions.Current.CheckPermissionStatusAsync(Permission.Storage);

                	if (photoStatus != PermissionStatus.Granted || storageStatus != PermissionStatus.Granted)
                	{
						var results = await CrossPermissions.Current.RequestPermissionsAsync(new[] { Permission.Photos, Permission.Storage });
						photoStatus = results[Permission.Photos];
                    	storageStatus = results[Permission.Storage];
                	}
					if (photoStatus == PermissionStatus.Granted && storageStatus == PermissionStatus.Granted)
					{

						var photo = await CrossMedia.Current.PickPhotoAsync(new Plugin.Media.Abstractions.PickMediaOptions
						{
							CompressionQuality = 92,
							PhotoSize = Plugin.Media.Abstractions.PhotoSize.Small
						});
						if (photo != null)
						{
							var stream = photo.GetStream();
							bool result = await App.HttpService.UploadLogo(stream);
							if (result)
							{
								logoImage.Source = ImageSource.FromStream(() =>
								  {
									  var stream1 = photo.GetStream();
									  photo.Dispose();
									  return stream1;
								  });
							}
						}
						return;
					}
				}
				else if(action.Equals("Take picture")){ 
					var cameraStatus = await CrossPermissions.Current.CheckPermissionStatusAsync(Permission.Camera);
					var storageStatus = await CrossPermissions.Current.CheckPermissionStatusAsync(Permission.Storage);
                	if (cameraStatus != PermissionStatus.Granted || storageStatus != PermissionStatus.Granted)
                	{
                    	var results = await CrossPermissions.Current.RequestPermissionsAsync(new[] { Permission.Camera, Permission.Storage });
						cameraStatus = results[Permission.Camera];
                    	storageStatus = results[Permission.Storage];
                	}
					if (cameraStatus == PermissionStatus.Granted && storageStatus == PermissionStatus.Granted)
					{
						var mediaOptions = new Plugin.Media.Abstractions.StoreCameraMediaOptions
						{
							Directory = "Logo",
							Name = "eshiplogo.jpg"
						};

						// Take a photo of the business receipt.
						var file = await CrossMedia.Current.TakePhotoAsync(mediaOptions);
						if (file != null) {
							var stream = file.GetStream();
							bool result = await App.HttpService.UploadLogo(stream);
							if (result){
								logoImage.Source = ImageSource.FromStream(() =>
								{
									var stream1 = file.GetStream();
									file.Dispose();
									return stream1;
								});
							}
						}
						return;
					}
				}

**Comment by jamesmontemagno** [comment] 2017-06-07 20:16
Fixed in beta. Duplicate of: https://github.com/jamesmontemagno/MediaPlugin/issues/265

**Closed by jamesmontemagno** 2017-06-07 20:16 UTC

**Comment by Cyqlblgy** [comment] 2017-06-08 02:09
Thanks @jamesmontemagno , updating to beta version solved the problem.

**Comment by lohitha123** [comment] 2018-02-07 04:45
Hi All,

I am using xam.plugin.media.3.1.3 version.. In ios it is not working properly...


**Information:**

First Time when click take photo-> it opens the camera-> I got the image and i can able to display on my content page.


Again when I click on take photo -> it is not appearing..


Please reopen this issue ...
