### ISSUE TITLE
Picking photo at iOS 10.3.3 (14G60) causes MediaService.PickPhotoAsync exception: UIKit.UIKitThreadAccessException: UIKit Consistency error: you are calling a UIKit method that can only be invoked from the UI thread.

### ISSUE THREAD

**Issue by Szymaniuk** [jamesmontemagno/MediaPlugin#393] opened 2017-11-09 11:45 UTC
## Bug Information

Version Number of Plugin: 3.0.2.175-beta
Device Tested On: Apple iPad Pro 9.7 Wi-Fi 32GB MLMP2FD/A
Simulator Tested On: <not_tested_yet>
Version of VS: 15.4.3
Version of Xamarin: 2.5.0.19271-pre2
Versions of other things you are using:

### Steps to reproduce the Behavior
Invoke:
`MediaFile mediaFile = await CrossMedia.Current.PickPhotoAsync();`
pick photo from iOS gallery picker.

### Expected Behavior
`mediaFile` object should be "mapped" to selected photo.

### Actual Behavior
`await CrossMedia.Current.PickPhotoAsync()` throws `MediaService.PickPhotoAsync exception: UIKit.UIKitThreadAccessException: UIKit Consistency error: you are calling a UIKit method that can only be invoked from the UI thread.`.
Full stacktrace:
https://gist.github.com/Szymaniuk/6af1d591b24615c474c406e093746290

### Code snippet
https://gist.github.com/Szymaniuk/bf95acec554dc709b8d47e4d05df409f

**Comment by Szymaniuk** [comment] 2017-11-09 12:07
Lol, I've just builded same code in **REALSE** mode, and it's working fine.
I'll try to rebuild again in **DEBUG** (where the issue occured) mode and try to reproduce it again.

**Comment by Szymaniuk** [comment] 2017-11-09 12:16
Confirmed after cleaning and rebuilding - it's crashing at **DEBUG** mode again.

**Comment by prashantvc** [comment] 2017-11-14 07:33
@Szymaniuk could you take a latest code from `issue-393` branch and test it locally from the source to see if it fixes the issue for you

**Comment by Szymaniuk** [comment] 2017-11-14 08:09
I've just moved to **issue-393** branch, created DLL's locally, and unfortunately able to reproduce the issue:
https://gist.github.com/Szymaniuk/f15abb393b6ea4d74d08543aea54b80b

**Comment by Szymaniuk** [comment] 2017-11-14 13:16
@jamesmontemagno , as I mentioned here https://github.com/jamesmontemagno/MediaPlugin/issues/393#issuecomment-344177355 , proposed fix is not working.

**Comment by prashantvc** [comment] 2017-11-14 14:52
@Szymaniuk that's rather strange! I will take another look at it

**Comment by prashantvc** [comment] 2017-11-15 07:00
@Szymaniuk I am not able to reproduce this. Could you put a break point here when debugging
https://github.com/jamesmontemagno/MediaPlugin/blob/198a3634b3b424f170408590a3323db62f88fd94/src/Media.Plugin.iOS/MediaPickerController.cs#L50

**Comment by jamesmontemagno** [comment] 2017-11-15 16:34
Yeah @Szymaniuk if you have the code, give us the line of code where it is blowing up.

**Comment by iupchris10** [comment] 2017-11-15 20:27
@jamesmontemagno @prashantvc 

UIKitThreadAccessException is throwing for me on line 30 of MediaPickerController.cs, which is called from line 51 of the same file.  Seems that setting Delegate must be done on the UI thread.

![screen shot 2017-11-15 at 3 25 57 pm](https://user-images.githubusercontent.com/5750525/32858388-56fc8712-ca19-11e7-8f4f-517099077ee3.png)

UIKitThreadAccessException - UIKit Consistency error: you are calling a UIKit method that can only be invoked from the UI thread.
Detailed Stack Trace..   at UIKit.UIApplication.EnsureUIThread () [0x00023] in /Users/builder/data/lanes/5520/51128b8c/source/xamarin-macios/src/UIKit/UIApplication.cs:88 
  at UIKit.UIImagePickerController.set_Delegate (Foundation.NSObject value) [0x00000] in /Users/builder/data/lanes/5520/51128b8c/source/xamarin-macios/src/build/ios/native/UIKit/UIImagePickerController.g.cs:456 
  at Plugin.Media.MediaPickerController.set_Delegate (Foundation.NSObject value) [0x00009] in /Users/cboehm/Projects/svn/[redacted]/iOS/temp/MediaPickerController.cs:30 
  at Plugin.Media.MediaPickerController.Dispose (System.Boolean disposing) [0x00037] in /Users/cboehm/Projects/svn/[redacted]/iOS/temp/MediaPickerController.cs:51 
  at Foundation.NSObject.Dispose () [0x00000] in ....

**Comment by iupchris10** [comment] 2017-11-15 20:34
Issue goes away for me when I change line 51 of MediaPickerController.cs to the following:
InvokeOnMainThread(() => Delegate = null);

I'm using an iPad Mini on iOS 10.2.1, by the way.

**Comment by prashantvc** [comment] 2017-11-16 06:24
@iupchris10 thanks for confirming this. James merged this fix few days ago

**Closed by prashantvc** 2017-11-16 06:24 UTC

**Comment by iupchris10** [comment] 2017-11-16 15:31
@prashantvc I'm afraid you may have misread my comment. I feel that the bug is still present even after the merge. It looks like in the commit that you fixed line 50, but line 51 needs run on the main thread as well.

**Comment by duzenko** [comment] 2017-11-16 16:36
I am getting UIKit Consistency errors in v3.0.2.181-beta.
Is it supposed to be fixed in that version?

**Comment by iupchris10** [comment] 2017-11-16 17:41
@duzenko The issue is still occurring on some devices in the latest version. I committed a fix today but waiting for it to be merged. Stay tuned.

**Comment by duzenko** [comment] 2017-11-17 09:20
.188 beta appears to have fixed it
