### ISSUE TITLE
Result of TakePhotoAsync is a solid grey colored rectangle

### ISSUE THREAD

**Issue by HopScotch47** [jamesmontemagno/MediaPlugin#225] opened 2017-04-26 22:59 UTC
Please fill out either the bug or feature request section and remove whatever section you are not using.

## Bug 

Version Number of Plugin:  2.6.2
Device Tested On: Lenovo Tab3 (TB3_X70F)

### Expected Behavior
Image is not stored in gallery but stored correctly in the pictures folder

### Actual Behavior
Image is stored in gallery but the image in the pictures folder only contains a solid shade of grey

### Steps to reproduce the Behavior
Just use TakePhotoAsync and check file in folder and gallery

Interesting side information... this happens on the default camera app that comes with the installation and only if the picture is taken right away, if I wait for ~10 seconds before taking the picture the image in the pictures folder is correct. 
Also, when I install an alternative camera app, the behaviour is correct.

**Comment by protokovich** [comment] 2017-04-27 10:18
same issue on Sony Xperia Z2.
If you do not wait ~7 seconds before tapping button in camera app, we get a bitmap of the size 1x1

**Comment by GingerSteve** [comment] 2017-05-29 22:33
This also happens on LG-G3s, identical behaviour to what @HopScotch47 described.
The image saved is a 1x1 grey square, approximately 630 bytes in size.

**Comment by protokovich** [comment] 2017-06-25 09:33
I see that the bug is fixed in 2.7+ versions.
but...
version 2.6.3.30 is the latest version with normal behavior setting orientation.
in 2.7+ if i take a photo in portrait rotation - returned photo always in landscape.
this is cricical for me. So i'm staying on 2.6.3.30

**Comment by jamesmontemagno** [comment] 2017-06-28 18:15
Seems to be fixed already. Can't reproduce locally at all.

**Closed by jamesmontemagno** 2017-06-28 18:15 UTC
