### ISSUE TITLE
[iOS] iOS 14, ObjectDisposedException MediaPickerController

### ISSUE THREAD

**Issue by Maxima078** [jamesmontemagno/MediaPlugin#910] opened 2020-11-25 13:19 UTC
An ObjectDisposedException is thrown when taking photo with `TakePhotoAsync`. However it doesn't crash and the photo can still be used.

Here is exception details:
`System.ObjectDisposedException Message=Cannot access a disposed object. Object name: 'MediaPickerController'.`

As you [proposed](https://github.com/jamesmontemagno/MediaPlugin#update-novemeber-2020) I tried to migrate to Xamarin.essentials.MediaPicker unfortunatly it is currently missing options (at least AllowCropping, DefaultCamera and RotateImage) and the multiple pictures pick is not proposed.

## Bug Information

Version Number of Plugin: 5.0.1
Device Tested On: iPhone XR
Version of VS: 16.7.7
Version of Xamarin: 16.7.000.463
Versions of other things you are using: Version of Xamarin;iOS: 14.2.0.12

### Steps to reproduce the Behavior
Call  `TakePhotoAsync`

### Expected Behavior
No exception thrown

### Actual Behavior
An ObjectDisposedException is thrown

### Screenshots
![image](https://user-images.githubusercontent.com/8363725/100232493-b2ce6480-2f28-11eb-8747-1cc18841bfc4.png)

**Comment by alsed42** [comment] 2021-03-17 21:15
Had a similar issue (probably the same) with the following stacktrace:

```
    Type: System.ObjectDisposedException
    Message: "Cannot access a disposed object.
Object name: 'Foundation.InternalNSNotificationHandler'."
    Stacktrace:
      at ObjCRuntime.ThrowHelper.ThrowObjectDisposedException (System.Object o) [0x00000] in /Users/xyz/_work/1/s/xamarin-macios/src/ObjCRuntime/ThrowHelper.cs:34 
      at ObjCRuntime.NativeObjectExtensions.GetNonNullHandle (ObjCRuntime.INativeObject self, System.String argumentName) [0x0001b] in /Users/xyz/_work/1/s/xamarin-macios/src/ObjCRuntime/INativeObject.cs:29 
      at Foundation.NSNotificationCenter.RemoveObserver (Foundation.NSObject observer) [0x00000] in /Users/xyz/_work/1/s/xamarin-macios/src/build/ios/native/Foundation/NSNotificationCenter.g.cs:179 
      at Plugin.Media.MediaPickerDelegate.RemoveOrientationChangeObserverAndNotifications () [0x00012] in d:\a\1\s\src\Media.Plugin\iOS\MediaPickerDelegate.cs:197 
      at Plugin.Media.MediaPickerDelegate.Canceled (UIKit.UIImagePickerController picker) [0x00000] in d:\a\1\s\src\Media.Plugin\iOS\MediaPickerDelegate.cs:100 
      at (wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)
      at UIKit.UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate) [0x00005] in /Users/xyz/_work/1/s/xamarin-macios/src/UIKit/UIApplication.cs:86 
      at UIKit.UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName) [0x0000e] in /Users/xyz/_work/1/s/xamarin-macios/src/UIKit/UIApplication.cs:65 
      at MyApplication.iOS.Application.Main (System.String[] args) [0x00024] in C:\SVN\MyApplication\MyApplication.iOS\Main.cs:19 
```

Versions:
Xam.Plugin.Media: 5.0.1
iOS: 14.4
Xamarin.Forms: 5.0.0.2012
Visual Studio: 16.9.1
IDB: 16.9.000.271

**Comment by zackrykalash** [comment] 2021-04-11 07:05
Had a metadata exception issue, when i set SaceMetaData = true, i got System.ObjectDisposedException Message=Cannot access a disposed object. Object name: 'MediaPickerController'.

So same issue, i don't know how to work around it

**Comment by 15mgm15** [comment] 2021-04-20 18:07
@zackrykalash Did you find a workaround for this?

**Comment by LennartIZIT** [comment] 2021-08-10 13:24
Anyone who has a workaround for this? I'm still having this issue.

**Comment by jamesmontemagno** [comment] 2022-02-10 03:37
I believe I have this fixed in next beta

**Comment by saamerm** [comment] 2022-03-07 06:10
@jamesmontemagno tried the latest pre-release version and it has the same issue

**Comment by saamerm** [comment] 2022-03-07 18:44
I cloned the project and used the library directly to try to dig into the source and this is where the error comes and why the app doesn't crash:
 
<img width="1137" alt="image" src="https://user-images.githubusercontent.com/8262287/157097484-39721868-2c47-41e1-baed-c850bf825f13.png">
This seems to be the step before:
<img width="730" alt="image" src="https://user-images.githubusercontent.com/8262287/157097649-bbf09e9d-0ca9-44f3-82a3-4e44f4614473.png">

**Comment by pspeybro** [comment] 2022-04-07 13:02
Is there any workaround or solution for this? 
I see that there 5.1.1-beta version, but the changelog does not include the changes yet.
@saamerm , did you check if it occurs without compression quality property?

**Comment by flipper09112** [comment] 2022-06-07 15:08
Hi! 
Some update?

**Comment by callumideagen** [comment] 2022-07-18 13:49
Hello,
Any update on this issue? 
Cannot use xamarin essentials as we need to support image compression :( .

**Comment by volcano619** [comment] 2022-08-26 10:55
> Had a similar issue (probably the same) with the following stacktrace:
> 
> ```
>     Type: System.ObjectDisposedException
>     Message: "Cannot access a disposed object.
> Object name: 'Foundation.InternalNSNotificationHandler'."
>     Stacktrace:
>       at ObjCRuntime.ThrowHelper.ThrowObjectDisposedException (System.Object o) [0x00000] in /Users/xyz/_work/1/s/xamarin-macios/src/ObjCRuntime/ThrowHelper.cs:34 
>       at ObjCRuntime.NativeObjectExtensions.GetNonNullHandle (ObjCRuntime.INativeObject self, System.String argumentName) [0x0001b] in /Users/xyz/_work/1/s/xamarin-macios/src/ObjCRuntime/INativeObject.cs:29 
>       at Foundation.NSNotificationCenter.RemoveObserver (Foundation.NSObject observer) [0x00000] in /Users/xyz/_work/1/s/xamarin-macios/src/build/ios/native/Foundation/NSNotificationCenter.g.cs:179 
>       at Plugin.Media.MediaPickerDelegate.RemoveOrientationChangeObserverAndNotifications () [0x00012] in d:\a\1\s\src\Media.Plugin\iOS\MediaPickerDelegate.cs:197 
>       at Plugin.Media.MediaPickerDelegate.Canceled (UIKit.UIImagePickerController picker) [0x00000] in d:\a\1\s\src\Media.Plugin\iOS\MediaPickerDelegate.cs:100 
>       at (wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)
>       at UIKit.UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate) [0x00005] in /Users/xyz/_work/1/s/xamarin-macios/src/UIKit/UIApplication.cs:86 
>       at UIKit.UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName) [0x0000e] in /Users/xyz/_work/1/s/xamarin-macios/src/UIKit/UIApplication.cs:65 
>       at MyApplication.iOS.Application.Main (System.String[] args) [0x00024] in C:\SVN\MyApplication\MyApplication.iOS\Main.cs:19 
> ```
> 
> Versions: Xam.Plugin.Media: 5.0.1 iOS: 14.4 Xamarin.Forms: 5.0.0.2012 Visual Studio: 16.9.1 IDB: 16.9.000.271 Device: iPhone 12 Pro (Simulator)

I'm getting a similar issue any luck with a workaround?

**Comment by saamerm** [comment] 2022-08-26 14:59
If anyone wants to give a stab at fixing this issue, let me know and I will give you all some pointers! @volcano619 @callumideagen @flipper09112 @pspeybro !

Essentially, (save your changes first), then use the debuggable version of this library:
1. clone this repository and 
2. add the CSProj from here https://github.com/jamesmontemagno/MediaPlugin/tree/master/src/Media.Plugin into your own solution. 
3. Edit references for each of your projects and include this project as a reference
4. Remove the MediaPlugin nuget package you have installed
5. Try to build and you should have no issues building

Then during the runtime
1. Place an exception catchpoint and you should see the exception is caught on Line 56 of the MediaPickerController in the iOS project
2. Try to fix the bug by playing around with the code.
3. Once you get there, let me know what you have tried!

**Comment by bijington** [comment] 2022-09-22 08:04
@saamerm I am currently digging in to this issue. Sadly an end user has seen it but I am yet to reproduce it in a development environment. Is it specific to a Pro device?

**Comment by bijington** [comment] 2022-09-22 10:02
> @saamerm I am currently digging into this issue. Sadly an end user has seen it but I am yet to reproduce it in a development environment. Is it specific to a Pro device?

@saamerm I have opened a draft PR with some experimental changes in it. I haven't been able to reliably reproduce the issue but as I mention in my PR the changes don't appear to make things any worse. 

Is there anyone that can reliably reproduce this that could test these changes out?

**Comment by volcano619** [comment] 2022-09-22 10:18
@bijington I can check, I'll report back if I'm able to reproduce it

**Closed** 2022-09-22 21:49 UTC

**Comment by bijington** [comment] 2022-09-26 14:06
@volcano619 thanks. I can confirm that so far my end user seeing this issue is unable to do so with the changes introduced. I must admit even they couldn't reproduce it regularly though
