### ISSUE TITLE
PickPhoto position in landscape orientation

### ISSUE THREAD

**Issue by knives85** [jamesmontemagno/MediaPlugin#280] opened 2017-06-21 15:19 UTC
When I use the PickPhotoAsync feature in landscape orientation, I get the popover not displayed in the center of the screen but on the left.
It can be something in my configuration that interfere with the plugin?

## Bug Information

Version Number of Plugin: 2.6.2
Device Tested On: iPad Mini 2
Simulator Tested On: iPad Air 2, iPad Pro
Version of Xamarin Forms: 2.1.0.6529

### Steps to reproduce the Behavior
Just call the PickPhotoAsync method
### Expected Behavior
The popover should appear in the center of the screen.

### Actual Behavior
The popover appears in the left of the screen when in landscape orientation

### Code snippet
var imageStream = await CrossMedia.Current.PickPhotoAsync();

### Screenshotst
![portrait](https://user-images.githubusercontent.com/9250910/27391845-52590b50-56a5-11e7-9a46-102d7c4487b2.png)

![screen](https://user-images.githubusercontent.com/9250910/27391805-352f9b70-56a5-11e7-8972-c78a594becbf.png)

**Comment by jamesmontemagno** [comment] 2017-06-21 17:28
Duplicate of https://github.com/jamesmontemagno/MediaPlugin/issues/274

**Closed by jamesmontemagno** 2017-06-21 17:28 UTC
