### ISSUE TITLE
Android: Application is restarted

### ISSUE THREAD

**Issue by shubhambhosale** [jamesmontemagno/MediaPlugin#193] opened 2017-03-09 11:06 UTC
## Application is restarted on Android when taking photo using camera 

Version Number of Plugin: 2.6.2
Device Tested On: Moto X Play
Simulator Tested On: 5" Marshmallow (6.0.0) XHDPI Phone

### Expected Behavior
Application should not be restarted & stays on current page.

### Actual Behavior
Application restarted from the first page i.e page set at MainPage in App.xaml.cs file and then goes to the OnAppearing() of each page upto the page where the TakePhotoAsync() is called.

I have attached my testing project copy.
[CameraTesting.zip](https://github.com/jamesmontemagno/MediaPlugin/files/830538/CameraTesting.zip)

**Comment by jamesmontemagno** [comment] 2017-03-09 16:13
Duplicate of https://github.com/jamesmontemagno/MediaPlugin/issues/155

also check your activity setting to change https://developer.android.com/guide/topics/manifest/activity-element.html#lmode

**Closed by jamesmontemagno** 2017-03-09 16:13 UTC

**Comment by shubhambhosale** [comment] 2017-03-10 10:26
Could you please suggest what activity settings i should use to prevent the app from restarting, I'm not getting it correctly.

**Comment by jamesmontemagno** [comment] 2017-03-10 18:09
Single Task is usually good: https://github.com/xamarinhq/app-evolve/blob/master/src/XamarinEvolve.Android/MainActivity.cs#L38
