### ISSUE TITLE
Camera crashing taking photos - Android

### ISSUE THREAD

**Issue by LeoJHarris** [jamesmontemagno/MediaPlugin#586] opened 2018-07-16 23:32 UTC
Issue - camera crashing and causing app to close or return to root page. Only tested on android for a android only app. Crashing with the sample as well

Not happening all the time but enough to make it annoying and whats making this really hard to figure out is there is no crash report happening and the logcat is spitting out a tone of information most of which not applicable either but have attached something to bottom to indicate the crash section I think

## Bug Information

Version Number of Plugin: 4.0.1.1
Device Tested On: 2 (Android 7.1.1 and 5.1.1)
Simulator Tested On: None tested
Version of VS: 15.7.5
Version of Xamarin: 3.1.0.637273

### Steps to reproduce the Behavior

Start the camera TakePhotoPicker().
Take photo.
Tap "Use photo" ... crashes.

### Expected Behavior

Should not crash but simply return to page that invoked the camera

### Actual Behavior

App is crashing and closing the app or sometimes returns to root page (restarting the app)

### Code snippet

```
 if (CrossMedia.Current.IsCameraAvailable && CrossMedia.Current.IsTakePhotoSupported)
            {
                MediaFile file = await CrossMedia.Current.TakePhotoAsync(new StoreCameraMediaOptions
                {
                    Directory = "laundry",
                    SaveToAlbum = true,
                    CompressionQuality = 80,
                    CustomPhotoSize = 50,
                    PhotoSize = PhotoSize.MaxWidthHeight,
                    MaxWidthHeight = 2500,
                    DefaultCamera = CameraDevice.Rear
                }).ConfigureAwait(true);

                if (file != default(MediaFile))
                {
                    byteArrayImages.Add(Utilities.ReadToEnd(file.GetStream()));
                    AddPhotosInPhotoGrid();
                }
                else
                {

                }
            }
            else
            {
                UserDialogs.Instance.Toast("Camera not supported");
            }
``` 

### Logcat

I might have narrowed down in the logcat to this snippet: 
https://gist.github.com/LeoJHarris/135be65438a8b264edf7029cc6326f96

On line 33 you'l see where the project is being killed: 

07-17 10:58:40.171: I/ActivityManager(2022): Process com.test.laundryapp (pid 13504) has died

Also see attached of gif of sample project from this repo, I have speed up 2x
![ezgif com-gif-maker 3](https://user-images.githubusercontent.com/5468757/42792831-451d0842-89cb-11e8-8de7-2901d9cbc3d7.gif)

**Comment by LeoJHarris** [comment] 2018-07-17 01:44
The image that is saves to my folder looks broken as well when I got to inspect the photo it took to my directory.

**Comment by Dids** [comment] 2018-07-23 12:17
I thought I was the only one seeing this. I initially thought it was due to a whitespace in the path (`/storage/emulated/0/Android/data/com.sisailmahuolto.tyomaarain2017/files/Pictures/Images/23.7.2018 12.11.09.jpg`), but if it's showing the same results even with a file stream, then I guess the file itself is corrupt?

Either way, it would be nice to have this fixed soon, or at least figure out a workaround for the current version.

**Comment by LeoJHarris** [comment] 2018-07-23 20:42
@Dids Nope the path should be fine, the photo sometimes gets corrupted it seems more often the not as well. The exception is being thrown in the TakePhotoAsync() before it even returns from the method. The stack trace is virtually returning nothing and logcat is very hard to pinpoint. The sample is having the same issue - surely a simple test would demonstrate this? 

In the meantime I have switched to this plugin: https://github.com/ThatCSharpGuy/Forms-FullCameraPage there is no Nuget package just download the source code and integrate that. 

Will switch back to this project when this issue gets fixed... Hopefully soon.

**Comment by ronnyhash** [comment] 2018-08-08 15:53
I'm having this issue as well, especially on LG phones released in the last year. Would be great to get a fix for this.

**Comment by LeoJHarris** [comment] 2018-08-08 20:51
@ronnyhash I'm using a Nokia 2 ta-1007

**Comment by FilipeTabosa** [comment] 2018-08-14 18:53
It is possible to be the same error presented on the following issue:
#286

**Comment by LeoJHarris** [comment] 2018-08-14 23:06
@FilipeTabosa I did see that issue as well. Is this issue even being looked into?

**Comment by LeoJHarris** [comment] 2018-08-14 23:12
I think this is the same issue. as the other issue mentions:

No crash is logged as the app technically doesn't crash, the memory is just freed and the app restarts.

**Comment by FilipeTabosa** [comment] 2018-08-16 11:36
@LeoJHarris They said that they were looking into it, but it has some time since the last statement they made.  From what I could see it happens when the phone needs to free some memory and closes the application in the process. To solve that I think the only way, for now, is to keep some "cache" on the phone and re-create all screens whenever the application is closed after taking a picture.

**Comment by nichojo89** [comment] 2018-08-30 18:40
We are also experiencing the same issue on an LG G6 Oreo only "Unfortunantly, Camera has stopped". I've reproduced this directly from Jame's GitHub project

**Comment by aymeric-apcurium** [comment] 2018-08-30 18:48
Exact same problem here with LG G6 running oreo,
Hockey App Crash report states:
"ResourcesImpl.loadDrawableForCookie"
android.content.res.Resources$NotFoundException: Drawable com.Apcurium.Alpha:mipmap/icon with resource ID #0x7f030000
Caused by: android.content.res.Resources$NotFoundException: File res/mipmap-anydpi-v26/icon.xml from drawable resource ID #0x7f030000

**Comment by ronnyhash** [comment] 2018-09-01 19:26
An update on this would be greatly appreciated. I'm getting more users with LG phones, and having this unresolved issue is starting to be very bad for my business. Is anyone monitoring this issue and looking to resolve it?

**Comment by aymeric-apcurium** [comment] 2018-09-05 17:40
@ronnyhash  I opened a ticket specifically for LG G6 if you wish to participate.
https://github.com/jamesmontemagno/MediaPlugin/issues/609

**Comment by mattcartwright** [comment] 2018-09-11 13:05
We've had reports of people with lg and Samsung devices getting this issue with our app.  

Our lg office phone now has the issue but it only started happening after I updated it to 8.1.  One thing I've noticed is that switching cameras back and forth (back camera --> front camera --> back camera) and then taking a photo seems to work every time.

**Comment by LeoJHarris** [comment] 2018-09-17 23:43
I was looking at the essentials lib from xamarin at: https://github.com/xamarin/Essentials and a proposal has been put forward from @jamesmontemagno for camera (take photo)

Not sure if this might just be a migration of this library towards that? 

https://github.com/xamarin/Essentials/issues/176

**Comment by LeoJHarris** [comment] 2018-10-18 03:32
@mattcartwright Actually I think just initially setting the camera to use the front is working fine, problem exists in the rear camera

**Comment by LeoJHarris** [comment] 2018-10-18 03:49
@mattcartwright I take that back, crashes only less with front camera from my experience.. Darn is there actually a camera plugin that works on Xamarin??

**Comment by kaoDev** [comment] 2018-11-09 16:22
I get the `...mipmap/icon with resource ID #0x7f030000` Error with a Pixel XL running Android 9 (front and rear camera).

The camera activity itself is running and I can take a photo, but the rest of the app has already crashed and it's not possible to select the photo and return it as a result.

**Comment by nichojo89** [comment] 2018-12-05 03:13
Hey guys, I was also having issues with LG H872 ad the LG G6 with the Plugin.Media plugin. You can use the below code to use a custom Xamarin.Android photo capture when device model is your problematic device, else it will use Plugin.Media.

@jamesmontemagno  I was wondering if Plugin.Media will be included in the new Xamarin.Essentials and if more of these device specific issues will be resolved?

Anyway here ya go devs...


Below goes in NetStandard project
-----------------------------------
your shared code method to take photo
var userDevice = CrossDeviceInfo.Current;
if (App.IsAndroid && userDevice.Model == "LG-H872" || App.IsAndroid && userDevice.Model == "LG-68")
{
    //Because of the variety of android devices having different camera apps, front/back, storage folder paths, etc...
    //We will only use our custom Xamarin.Android style image capture for the LG G6 and add more as we find more 
    //devices that are unsupported by the Plugin.Media plugin
    await DependencyService.Get<ITakePhotoDroid>().RetreivePhoto();
    //prevent memory issues
    App.appModel.PropertyChanged -= UpdateProfilePicAndroid;
    //react to new photo being captured, I update a property in my App.cs from OnActivityResult override
    App.appModel.PropertyChanged += UpdateProfilePicAndroid;
}
else {
    //Plugin.Media style image capture
}



Create ITakePhotoDroid.cs file
public interface ITakePhotoDroid
{
    Task RetreivePhoto();
}

Below goes in Xamarin.Android project
-------------------------------------
Create TakePhotoDroid.cs

[assembly:Xamarin.Forms.Dependency(typeof(TakePhotoDroid))]
namespace My.Mobile.Droid
{
    public class TakePhotoDroid : Activity, ITakePhotoDroid
    {
        public static Java.IO.File _file;
        public const int RequestCode = 270;
        public static byte[] _pic;
        public static byte[] pic
        {
            get { return _pic; }
            set {
                if (value != null)
                {
                    _pic = value;
                    //notify shared code to update SQLite, API, & UI
                    //This is where you should notify NetStandard project of photo captured
                    My.Mobile.App.appModel.NewProfilePic = value;
                }
            }
        }
        public async Task RetreivePhoto()
        {
            if (IsThereAnAppToTakePictures())
            {
                await TakeAPicture();
            }
        }
        private bool IsThereAnAppToTakePictures()
        {
            Intent intent = new Intent(MediaStore.ActionImageCapture);

            var context = global::Android.App.Application.Context;
            PackageManager manager = context.PackageManager;

            IList<ResolveInfo> availableActivities =
                manager.QueryIntentActivities(intent, PackageInfoFlags.MatchDefaultOnly);
            return availableActivities != null && availableActivities.Count > 0;
        }

        private async Task TakeAPicture()
        {
            try
            {
                Intent intent = new Intent(MediaStore.ActionImageCapture);

                StrictMode.VmPolicy.Builder builder = new StrictMode.VmPolicy.Builder();
                StrictMode.SetVmPolicy(builder.Build());
                _file = new Java.IO.File(
                Android.OS.Environment.GetExternalStoragePublicDirectory(
                Android.OS.Environment.DirectoryPictures), "Pictures");

                var file = new Java.IO.File(_file, String.Format("MyProfilePic_{0}.jpg", Guid.NewGuid()));
                intent.PutExtra(MediaStore.ExtraOutput, Android.Net.Uri.FromFile(_file));





                var mainActivity = MainActivity.Context as MainActivity;
                mainActivity.StartActivity(intent, OnActivityResult);        
            }
            catch (Exception ex)
            {

            }
        }
        public static Bitmap RotateBitMap(Bitmap image)
        {
            var matrix = new Matrix();
            matrix.PostRotate(-90);
            return Bitmap.CreateBitmap(image, 0, 0, image.Width, image.Height, matrix, true);
        }
    }
}
Create a BitmapHelpers.cs file
public static class BitmapHelpers
    {
        public static Bitmap LoadAndResizeBitmap(this string fileName, int width, int height)
        {
            // First we get the the dimensions of the file on disk
            BitmapFactory.Options options = new BitmapFactory.Options { InJustDecodeBounds = true };
            BitmapFactory.DecodeFile(fileName, options);

            // Next we calculate the ratio that we need to resize the image by
            // to fit the requested dimensions.
            int outHeight = options.OutHeight;
            int outWidth = options.OutWidth;
            int inSampleSize = 1;

            if (outHeight > height || outWidth > width)
            {
                inSampleSize = outWidth > outHeight
                                   ? outHeight / height
                                   : outWidth / width;
            }

            // Now we will load the image and have BitmapFactory resize it for us.
            options.InSampleSize = inSampleSize;
            options.InJustDecodeBounds = false;

            Bitmap resizedBitmap = BitmapFactory.DecodeFile(fileName, options);
            //ROTATION START
            // Images are being saved in landscape, so rotate them back to portrait if they were taken in portrait
            Matrix mtx = new Matrix();
            ExifInterface exif = new ExifInterface(fileName);


            var orientation = (Android.Media.Orientation)exif.GetAttributeInt(ExifInterface.TagOrientation, (int)Android.Media.Orientation.Undefined);

            switch (orientation)
            {
                case Android.Media.Orientation.Undefined: // Nexus 7 landscape...
                    break;
                case Android.Media.Orientation.Normal: // landscape
                    break;
                case Android.Media.Orientation.FlipHorizontal:
                    break;
                case Android.Media.Orientation.Rotate180:
                    mtx.PreRotate(180);
                    resizedBitmap = Bitmap.CreateBitmap(resizedBitmap, 0, 0, resizedBitmap.Width, resizedBitmap.Height, mtx, false);
                    mtx.Dispose();
                    mtx = null;
                    break;
                case Android.Media.Orientation.FlipVertical:
                    break;
                case Android.Media.Orientation.Transpose:
                    break;
                case Android.Media.Orientation.Rotate90: // portrait
                    mtx.PreRotate(90);
                    resizedBitmap = Bitmap.CreateBitmap(resizedBitmap, 0, 0, resizedBitmap.Width, resizedBitmap.Height, mtx, false);
                    mtx.Dispose();
                    mtx = null;
                    break;
                case Android.Media.Orientation.Transverse:
                    break;
                case Android.Media.Orientation.Rotate270: // might need to flip horizontally too...
                    mtx.PreRotate(270);
                    resizedBitmap = Bitmap.CreateBitmap(resizedBitmap, 0, 0, resizedBitmap.Width, resizedBitmap.Height, mtx, false);
                    mtx.Dispose();
                    mtx = null;
                    break;
                default:
                    mtx.PreRotate(90);
                    resizedBitmap = Bitmap.CreateBitmap(resizedBitmap, 0, 0, resizedBitmap.Width, resizedBitmap.Height, mtx, false);
                    mtx.Dispose();
                    mtx = null;
                    break;
            }
            //ROTATION END


            return resizedBitmap;
        }

    }

Below methods go in MainActivity
protected override void OnActivityResult(int requestCode, Result resultCode, Intent data)
{
    base.OnActivityResult(requestCode, resultCode, data);
    if (requestCode == TakePhotoDroid.RequestCode)
    {
        if (_resultCallback != null)
        {
            _resultCallback(requestCode, resultCode, data);
            _resultCallback = null;

            //User has selected an image so set TakePhotoDroid.pic
            Bitmap bitmap = TakePhotoDroid._file.Path.LoadAndResizeBitmap(200, 300);

            using (var stream = new MemoryStream())
            {
                bitmap.Compress(Bitmap.CompressFormat.Png, 0, stream);
                TakePhotoDroid.pic = stream.ToArray();
            }
            //Dispose of the Java side bitmap.
            GC.Collect();
        }
    }
}
public void StartActivity(Intent intent, Action<int, Result, Intent> resultCallback)
{
    _resultCallback = resultCallback;
    //Open Camera Application
    StartActivityForResult(intent, TakePhotoDroid.RequestCode);
}

**Comment by mscott161** [comment] 2019-01-21 17:49
The issue with the LG G6 Camera Crashing has to do with the intent.PutExtra in the UseFrontCamera and UseBackCamera.
The LG G6 allows only the following call for the back camera
intent.PutExtra("android.intent.extras.CAMERA_FACING", 0);

You can do an if condition but for my implementation I have all android above 7.0 and accept the CAMERA_FACING extra with 0 for back and 1 for front to work.

A great way to allow this to be fixed for the LG and still work with the other phones would be to allow the DefaultCamera property to be -1 and change the if condition on the MediaPickerActivity to skip the UseFrontCamera and the UseBackCamera if the value is -1.

**Comment by gsemenov** [comment] 2019-03-18 14:25
Yes, your solution works, when I comment line:
intent.PutExtra(extraUserFront, false);
and run the demo it works well on the LG, but I'm not sure how it will work for other devices/android versions
Did anyone make fixes here in the plugin? 
![image](https://user-images.githubusercontent.com/5072093/54536992-c929cc00-49a2-11e9-9c32-6d7b46acae1d.png)

**Comment by LeoJHarris** [comment] 2019-03-19 23:26
@mscott161 suggestion to do PR, it would be great to see this issue finally fixed 👍

**Comment by Cklauber** [comment] 2019-04-18 23:57
So, does this happen due to the size of the screen of the device?

**Comment by gsemenov** [comment] 2019-04-19 07:20
I think the size of the screen doesn't matter here, I didn't see any addictions with it.

**Comment by welshrat77** [comment] 2019-04-24 17:05
Same Problem here, I am reverting to the old Xamarin Mobile package as I know that works, any chance this will get fixed ?

**Comment by brepetti** [comment] 2019-04-26 19:55
This resolved our issue with LG devices.  The camera app would crash when using the Media Plugin.

Commenting out the lines above did the trick. 

This problem has existed for a few months now.  Nice to see a resolution.

**Comment by VictorK1902** [comment] 2019-07-01 17:11
Any update on this?

**Comment by jaytilly** [comment] 2019-07-03 22:42
PR for fix at https://github.com/jamesmontemagno/MediaPlugin/pull/715

The fix is to first check that the intent extra needs to be set initially.  If it doesn't need to be set, the putextra is skipped. When switching between back->front and vice-a-versa, the putextra works just fine...it was just the initial set when the extra is already false. Not sure what is going on under the LG covers but my guess is some state-machine is not happy.

This shouldn't have any negative side-effects and should fix the issues with the LG. 

Tested on LG G7 that had the same problem.

**Comment by Eltee-Taiwo** [comment] 2019-07-08 06:01
> PR for fix at #715
> 
> The fix is to first check that the intent extra needs to be set initially. If it doesn't need to be set, the putextra is skipped. When switching between back->front and vice-a-versa, the putextra works just fine...it was just the initial set when the extra is already false. Not sure what is going on under the LG covers but my guess is some state-machine is not happy.
> 
> This shouldn't have any negative side-effects and should fix the issues with the LG.
> 
> Tested on LG G7 that had the same problem.

I saw that this PR had been merged so I cloned the repo, built the solution and added the DLLs directly to my project to test it. Unfortunately it looks like I'm still suffering the same issue...Front Camera takes the picture without problem, but using the rear camera just crashes the app.

I was using the nuget package earlier (which didn't have your changes) so I'm hoping that maybe the DLLs on my test device didn't update. I'll try a clean install tomorrow and let you know. Fingers crossed / knock on wood. I really need this to work.

**Comment by jaytilly** [comment] 2019-07-08 16:45
> I saw that this PR had been merged so I cloned the repo, built the solution and added the DLLs directly to my project to test it. Unfortunately it looks like I'm still suffering the same issue...Front Camera takes the picture without problem, but using the rear camera just crashes the app.
> 
> I was using the nuget package earlier (which didn't have your changes) so I'm hoping that maybe the DLLs on my test device didn't update. I'll try a clean install tomorrow and let you know. Fingers crossed / knock on wood. I really need this to work.

It seems like I had the same issue at first, especially since the nuget name and dll are different (if I remember correctly). I ended up adding the project to the solution I needed so that I could step through, debug and make sure it was indeed working on the LG. Once I got that working, I simply built the release version and referenced it. I'd been using the fix for a few months before submitting and it seems to be working fine. If you need a hail-mary solution, try commenting out the line with 'intent.PutExtra(extraUserFront, false);'. I ran it like that for a while and didn't see any side-effects, at least on that device.

**Comment by VictorK1902** [comment] 2019-07-08 23:31
Installing 4.3.1-beta fixed it for me. Thanks everyone.

**Comment by LeoJHarris** [comment] 2019-07-09 00:02
Great to hear we have a fix. @jamesmontemagno when you are totally happy with this fix can we include it in a stable release. Im always a little nervious installing beta packages into applications being used in live instances.

**Comment by Eltee-Taiwo** [comment] 2019-07-09 01:38
> It seems like I had the same issue at first, especially since the nuget name and dll name are different (if I remember correctly). I ended up adding the project to the solution I needed so that I could step through, debug and make sure it was indeed working on the LG. Once I got that working, I simply built the release version and referenced it. I'd been using the fix for a few months before submitting and it seems to be working fine. If you need a hail-mary solution, try commenting out the line with 'intent.PutExtra(extraUserFront, false);'. I ran it like that for a while and didn't see any side-effects, at least on that device.

Figured it out. If you set the Default camera to the front facing camera, you never call UseBackCamera and instead call UseFrontCamera.

Created a pull request to add the intent check there as well

**Closed** 2019-07-09 23:40 UTC
Labels: up-for-grabs

**Comment by fadaEntrepidus** [comment] 2019-07-26 15:06
Hi guys. I've a device LG G7 Android 8.0.0 and I installed the version 4.0.1.5 and the error continue, when the user take a photo say: "Camera has stopped". Any idea what's happening?

**Comment by LeoJHarris** [comment] 2020-05-13 03:43
Hi all appears this issue is still randomly being thrown. After taking photo sometimes app crashes and restarts.

**Comment by Eltee-Taiwo** [comment] 2020-05-13 03:44
I occasionally get this error every now and then but from all my testing it only seems to happen on LG phones.

**Comment by LeoJHarris** [comment] 2020-05-13 03:48
@Eltee-Taiwo thats a shame. But Im using a Nokia 2 (TA-1007) and this happens often with the app crashing.

**Comment by LeoJHarris** [comment] 2020-05-13 03:49
Is there a reliable camera library that actually works with Xamarin 100% of the time?

**Comment by Eltee-Taiwo** [comment] 2020-05-13 03:51
None that I've found. But if you find one please let me know haha

**Comment by LeoJHarris** [comment] 2020-05-13 03:54
@Eltee-Taiwo I feel Ill wint the lottery before that ever happens. But ya never know...

**Comment by Clauber** [comment] 2020-05-13 04:13
That's one of the reasons why I migrated to React Native

**Comment by LeoJHarris** [comment] 2020-05-13 04:15
@Clauber I dont even blame you. What are you meant to do otherwise if an app needs camera functionality to work on any android device. Frustrating.

**Comment by LeoJHarris** [comment] 2020-05-13 04:16
Oh well custom renderer it its...

**Comment by Eltee-Taiwo** [comment] 2020-05-13 04:17
What's the learning curve on either of those options? That is migrating to React Native and Using a custom renderer.

**Comment by LeoJHarris** [comment] 2020-05-13 04:32
@Eltee-Taiwo agree with what your saying there, my only issue with these things is the Xamarin Community has been asking for working camera functionality for a while now and this issue I raised nearly 2 years ago is still occuring. I am however hopeful camera plugin will be included in the Xamarin framework someday.

**Comment by brepetti** [comment] 2020-05-13 04:48
LG devices suck.  We found it was an issue with default camera app.  When installing open camera it works fine.  Not the best solution but LG is doing something funky.  I thought they had this fixed in latest version / pre release.  We haven't seen it in a while.

**Comment by LeoJHarris** [comment] 2020-05-13 04:51
@brepetti we are using a nokia phone, I also thought this was resolved, but revisited on another project and its begun crashing as it was when I opened this issue.

**Comment by brepetti** [comment] 2020-05-13 04:55
If you install open camera does that resolve? I know that's not a fix but might be a hint to problem.  If I remember the fix had something to do with default camera selection being incorrect. Also check your file provider info is defined correct.

**Comment by LeoJHarris** [comment] 2020-05-13 05:16
@brepetti thats a good idea, at least it would indicate where the potential issue lay, Ill check on the file provider. With regards to default camera selection, are you meaning the front vs back camera being incorrect?

**Comment by brepetti** [comment] 2020-05-13 05:19
Yes.  There was a difference in how LG camera app needed the flag set in the intent if I recall.  Just a wild guess the Nokia could be similar.  Will try to look up the info tomorrow.  It's on a closed issue somewhere on here.

**Comment by LeoJHarris** [comment] 2020-05-13 05:21
@brepetti appreciated, Ill dig that to because I think I saw it as well a while back and it seemed like the silver bullet. Lastly did you clone this repo and just make that change and it resolved your issue even on LG?

**Comment by LeoJHarris** [comment] 2020-05-13 05:23
@brepetti both crashing even before I can take a photo as the plugin initalizes and also can crash after photo taken.

**Comment by brepetti** [comment] 2020-05-13 05:24
I think the 5.0 release solved it.  At least for LG.  On the LG you could not open camera at all.  

There was a difference with how the file provider should be defined too for different vendors.  If I can find the info tomorrow I'll post.  I'm on my phone right now.

**Comment by LeoJHarris** [comment] 2020-05-13 05:26
@bpater-tp that'd be great hugely appreciated.

**Comment by LeoJHarris** [comment] 2020-05-14 01:05
@brepetti Working through this issue again, open camera doesnt work. Also commented out the below with no luch as previously mentioned https://github.com/jamesmontemagno/MediaPlugin/issues/586#issuecomment-473931382:

IntentExtraExtensions.cs

```csharp
           public static void UseBackCamera(this Intent intent)
        {
            // Android before API 25 (7.1)
            intent.PutExtra(extraFrontPre25, (int)CameraFacing.Back);

            // Android API 25 and up
            // intent.PutExtra(extraBackPost25, 1);

            //var isIntentNeeded = intent.GetBooleanExtra(extraUserFront, false);
            //if (isIntentNeeded)
            //intent.PutExtra(extraUserFront, false);
        }
```

**Comment by LeoJHarris** [comment] 2020-05-14 02:03
@brepetti hmm maybe the above does work but I think setting dex compiler to `dx` and no code shrinker makes a difference as well as I still got crashing occur with dex compiler to d8 and code shrinker to r8 with the above code commented out.

With Dex compiler set to 'dx' and code shrinker 'none' with the above code commented out I've been able to test app without it crashing in release mode. I would be interest if others have had issues as I had and this method worked for them also.

**Comment by LeoJHarris** [comment] 2020-05-14 04:39
@brepetti In the end I've opted to use the old xlabs implementation which seems to work fine for now. For iOS I'm using this plugin.

I had to add this into the renderer constructor although:

```csharp
public MediaPicker() : base()
        {
            IsPhotosSupported = true;
            IsVideosSupported = true;
    
            // Lines added
            StrictMode.VmPolicy.Builder builder = new StrictMode.VmPolicy.Builder();
            StrictMode.SetVmPolicy(builder.Build());
        }
```

**Comment by tartulab** [comment] 2020-11-25 13:43
does anyone find a proper solution?
