### ISSUE TITLE
Restarting the app while taking photo and after clicking OK

### ISSUE THREAD

**Issue by Packiaseelan** [jamesmontemagno/MediaPlugin#382] opened 2017-10-26 04:33 UTC
Hi james,

## Bug Information

Version Number of Plugin:  xam.plugin.media version 2.6.2
Device Tested On: (MotoG 3rd Gen, MotoG 2rd Gen)
Simulator Tested On: 
Version of VS: Microsoft Visual studio Professional 2015  
Version of Xamarin: 4.3.0.784
Versions of other things you are using: 

### Steps to reproduce the Behavior

while taking photo after clicking "tick" or "OK".
restarting the app.

### Expected Behavior

With out restart have to next process of my work.

### Actual Behavior

restarting the app.

### Code snippet
```csharp
var file = await CrossMedia.Current.TakePhotoAsync(new Plugin.Media.Abstractions.StoreCameraMediaOptions
  {
        Directory = "DefectPhoto",
        Name = "Defect.png",
        PhotoSize = Plugin.Media.Abstractions.PhotoSize.Small,
        DefaultCamera = Plugin.Media.Abstractions.CameraDevice.Rear
    });
    if (file == null)
        return;
    AppClass.ApplicationCore.DefectPath1 = file.Path;
    AppClass.ApplicationCore.DefectStream1 = file.GetStream();
    file.Dispose();

```
### Screenshots

1. Taking photo alert
![1](https://user-images.githubusercontent.com/28643800/32035087-52f857a8-ba34-11e7-8337-5a5e467c01e7.png)
2. Camera Open
![2](https://user-images.githubusercontent.com/28643800/32035088-5334cb98-ba34-11e7-9702-66235ce14533.png)
3. Captured picture
![3](https://user-images.githubusercontent.com/28643800/32035090-5370f78a-ba34-11e7-9040-1f7b1d76908f.png)
4. After click tick mark getting black screen
![4](https://user-images.githubusercontent.com/28643800/32035091-53aba240-ba34-11e7-82c5-7fd554ebdac1.png)
5. App Restarting
![5](https://user-images.githubusercontent.com/28643800/32035092-53ea2c54-ba34-11e7-8dd0-b564896a91ab.png)

Please provide me a valid solution to me

Thanks in Advance

**Comment by prashantvc** [comment] 2017-10-26 05:09
@Packiaseelan I am not able to reproduce this issue on my test devices? What version of Android are you using? Make sure you have appropriate permission to capture the picture.

Could you share the adb logs from the your device it will help us to troubleshoot the [issue](https://developer.xamarin.com/guides/android/deployment,_testing,_and_metrics/android_debug_log/)

**Comment by Packiaseelan** [comment] 2017-10-26 05:36
Hi @prashantvc,

I have given the appropriate permission to capture the picture.
It's working fine in other devices, but it doesn't work in the below mentioned devices and android version
1. Moto G (2nd Generation) - Android 5.1  
2. Moto G (3rd Generation) - Android 6.0.1

App doesn't crash, instead it restart the app, so there is no crash report.

Thanks for your replay,

**Comment by jamesmontemagno** [comment] 2017-10-26 05:49
What is your [Activity] attribute look like on your main activity?

**Comment by Packiaseelan** [comment] 2017-10-26 06:08
FormsApplicationActivity

**Comment by jamesmontemagno** [comment] 2017-10-26 16:37
I need the stuff above it... should look like:
```
    [Activity(Label = "@string/app_name",
    Icon = "@mipmap/ic_launcher",
    LaunchMode = LaunchMode.SingleTask,
    ConfigurationChanges = ConfigChanges.ScreenSize | ConfigChanges.Orientation)]
```

**Comment by Packiaseelan** [comment] 2017-10-27 04:14
Apologize @jamesmontemagno,

I misunderstood, 
the following is the stuff, that I used in my MainActivity.

```
[Activity(Label = "@string/app_name", 
MainLauncher = false, 
Icon = "@drawable/icon",
ConfigurationChanges = ConfigChanges.ScreenSize | ConfigChanges.Orientation, 
WindowSoftInputMode = SoftInput.AdjustPan | SoftInput.StateHidden)]
```

**Comment by jamesmontemagno** [comment] 2017-10-28 10:43
Do you have "Don't Keep Activities" on in your android developer settings?

**Comment by Packiaseelan** [comment] 2017-10-29 05:28
Nothing like that,

This issue not frequently happen, but eventually happen in Samsung (Galaxy Tab Active) android version 5.1.1 device also

**Comment by jamesmontemagno** [comment] 2017-10-29 20:44
Marking as duplicate of https://github.com/jamesmontemagno/MediaPlugin/issues/286

**Closed by jamesmontemagno** 2017-10-29 20:44 UTC
Labels: in-review, need-more-info

**Comment by thanderOliveira** [comment] 2020-08-13 15:02
> Do you have "Don't Keep Activities" on in your android developer settings?

James, where do I check that "Don't Keep Activities" settings? 

My clients are facing that same issue on asus smartphones, but I was not able to simulate. 
The smartphone has 2gb of RAM and the storage is empty, so it doesnt look like a RAM or stoprage issue.
Android version is 8.0 and 9.0
ASUS_A001D
ASUS_X00RD

My Activity is as follows:
    [Activity(Label = "Auvo",
               Icon = "@drawable/icon_roxo",
               Theme = "@style/MainTheme",
               MainLauncher = false,
               ScreenOrientation = ScreenOrientation.Portrait,
               ConfigurationChanges = ConfigChanges.ScreenSize | ConfigChanges.Orientation)]

**Comment by AndreSlim** [comment] 2020-11-19 01:59
> > Do you have "Don't Keep Activities" on in your android developer settings?
> 
> James, where do I check that "Don't Keep Activities" settings?

I had the same problem, you can find that setting within the developer options

![LzIyry4vfh](https://user-images.githubusercontent.com/24845037/99611021-81a9dd80-29d8-11eb-87dc-2b8ddac1b186.png)

**Comment by mclucky** [comment] 2020-11-19 06:27
The crash scenario after taking pictures is still an issue ->
https://github.com/jamesmontemagno/MediaPlugin/issues/900

**Comment by Bliitze** [comment] 2021-04-22 02:52
Same problem.
