### ISSUE TITLE
4.4.5-beta iOS 13.2 Image result rotated 90 or 180 degree

### ISSUE THREAD

**Issue by Jacko1394** [jamesmontemagno/MediaPlugin#760] opened 2019-10-18 03:53 UTC
Hi James,

Thanks for pushing out 4.4.3-5 betas quickly!
iOS 13.2 doesn't crash when tapping 'Use Photo' anymore 👍 but if I take a portrait image, the result ends up rotated 90.

Taking a landscape image works one way, but the other way will rotate 180 upside-down.

Apple making things difficult... (iPhone 8)

**Comment by Jacko1394** [comment] 2019-10-18 09:14
Still seems to be having rotation issues with 4.4.6-beta

**Comment by Jacko1394** [comment] 2019-10-18 10:32
So with SaveToAlbum=true, the photo is saved in the correct orientation, but in my Forms app the ImageSource displays wrong for portrait images... 🤔

**Comment by jamesmontemagno** [comment] 2019-10-19 07:40
Are you using "PickPhoto" or "PickPhotos"?

**Comment by Jacko1394** [comment] 2019-10-20 23:23
'PickPhoto' and 'PickPhotos' are both working, the rotation issue happens when using 'TakePhoto', the photo result after tapping 'Use Photo' gets rotated.

**Comment by Kiitoksia** [comment] 2019-10-24 15:19
We had the same issue, but the version of iOS did not matter (this is happening on 12.4.X), so I'm not entirely sure this is the same problem.  
Once I set AllowCropping=false, then the results came through in the correct rotation.

**Comment by MitchBomcanhao** [comment] 2019-10-24 16:01
using media plugin 4.0.1.5, with the same app build, also having issues.
We take/pick an image and generate a thumbnail based on the properties of the original image.
- iOS 13.2 has that image rotated 90 degrees to the left. (iPhone XS Max)
- iOS 13.1.2 has no issues (iPhone X)
- iOS 12.4 has no issues (iPhone 5s)

**Comment by OPunktSchmidt** [comment] 2019-10-28 13:36
I can confirm this problem too. The image saved to the album is rotate correctly but the ImageStream is rotated wrong. Only on iOs, Android works.

**Comment by hponaganti** [comment] 2019-10-29 15:08
Looks only beta updates are being done. Is beta safe to use  in Production Environment.  When will be a release to the nuget ?

**Comment by clintonrocksmith** [comment] 2019-10-29 22:43
I think it's due to the EXIF data being stripped out from the photo(s) as they're parsed back to the main application.  The EXIF data holds information about how to rotate the photo.

**Comment by ronnyhash** [comment] 2019-10-30 11:23
My users started to complain about this issue, so I tested it myself. I'm experiencing this exact issue after updating to iOS 13.2. Any possibility of a fix for this soon? My production app is suffering.

**Comment by ronnyhash** [comment] 2019-11-07 00:24
@jamesmontemagno Hey James, we really appreciate this plugin, but right now it cannot be used at all for iOS 13.2. This image rotation issue is Critical. It isn't possible to take an image with the correct rotation, and it is affecting all users. Can we please get an update on this?

I tried setting AllowCropping to false, but that didn't help. I tried setting SaveToAlbum to true, but that didn't work either.

We really need a fix for this fast! This has been a know issue for a couple weeks now. Please help!

**Comment by VictorK1902** [comment] 2019-11-07 17:44
Some of our users also experience this issue after upgrading to 13.2. I'm currently using 4.3.1-beta.

**Comment by brettchangus** [comment] 2019-11-07 23:13
Same problem here on iOS 13.2.2 + 4.0.1.5. Worked fine on iOS 13.1.2.

**Comment by dhewitson** [comment] 2019-11-08 02:27
Similar problem here with iOS 13.2 and plugin version 4.0.1.5
EXIF Data is missing on images saved using the plugin.

**Comment by klogeaage** [comment] 2019-11-10 21:32
Yes, we also see this problem on iOS 13.2. No EXIF data no matter whether you pick photo or take a new. This is pretty serious :-(.

**Comment by jveltd** [comment] 2019-11-11 11:00
We're also seeing this issue which is isolated to iOS 13.2.x

Tested on many iOS devices and after updating from 13.1.x to 13.2.x the images are now rotated.  

Is there an ETA on a fix for this please?

**Comment by jveltd** [comment] 2019-11-11 11:26
As a work around, if you set the following:

`SaveMetaData = false`

Then this will not rotate the image e.g. 

```
var photo = await CrossMedia.Current.TakePhotoAsync(new Plugin.Media.Abstractions.StoreCameraMediaOptions
{
  Name = "temp.jpg",
  PhotoSize = Plugin.Media.Abstractions.PhotoSize.MaxWidthHeight,
  MaxWidthHeight = 600,
  DefaultCamera = Plugin.Media.Abstractions.CameraDevice.Rear,
  CompressionQuality = 92,
  AllowCropping = true,
  SaveMetaData = false,
  SaveToAlbum = false
});
```

**Comment by klogeaage** [comment] 2019-11-11 11:45
Yes, but unfortunately the ability to read the metadata (EXIF)  from the picked file is a significant feature in our use of the plugin.
But thanks for the information.

**Comment by mnidhk** [comment] 2019-11-11 14:02
I can confirm this problem too. 
iOS 13.2 fixed some other issues for me but breaks this one.
Is it a bug in iOS13.2 or in this plugin!?
"SaveMetaData = false" works for me as a workaround for now

**Comment by vksuman** [comment] 2019-11-12 11:35
This problem is with iOS13 and  4.0.1.5 and any phone. We have experienced this issue with iPhone 5S, 6, 6S and 7.  We can't use SaveMetaData = false as metadata (EXIF) from the picked file is a significant feature for our app.

Could we have fix for this bug ASAP please???

**Comment by jamesmontemagno** [comment] 2019-11-12 21:37
Thanks @klogeaage for the repro of the built in image. I do see that being rotated weirdly.

It looks like the exif data is coming in just fine on the file, so if you using a library that reads the exif data it will be there.

Else, it looks like you may need to use: GetStreamWithImageRotatedForExternalStorage

![image](https://user-images.githubusercontent.com/1676321/68712889-80d2a600-0551-11ea-879b-70bb9a1a7efe.png)

When I use this it is just fine.

**Comment by jamesmontemagno** [comment] 2019-11-12 22:09
So, this looks like it is a bug with iOS 13.2, when calling:

```csharp
return UIImage.FromImage(cgi, 1.0f, orientation);
```

This function is called when you resize the image. If you mark the image as: PhotoSize = PhotoSize.Full you will not see the rotation at all when using the normal `GetStream`

So, if you are resizing the image you should request the rotated image back to display. If you are not then you can use the normal stream.

A question I have though is if anyone is experiencing this in applications compiled against Xcode 10 and iOS 12 or is everyone compiling against Xcode 11 and iOS 13?

**Comment by jamesmontemagno** [comment] 2019-11-12 22:14
After talking with the team and looking at the bindings, I really think that this is an iOS 13.2 bug and not a bug in the library itself. I have walked through a few work arounds for everyone here to validate in your own app.

**Comment by jveltd** [comment] 2019-11-12 22:16
Thanks for the update James.  I guess we can all feed this back to Apple for them to investigate.

**Comment by dhewitson** [comment] 2019-11-12 22:17
Thanks James, the workarounds are enough for us. 
Just an FYI we're compiling against XCode 11 and iOS 13

**Comment by jamesmontemagno** [comment] 2019-11-12 22:24
Alright, mind blown here.....

Apple decided to randomly remove an API from iOS 13:

```csharp
if(UIDevice.CurrentDevice.CheckSystemVersion(13, 0))
                {
                    transform = new CILanczosScaleTransform
                    {
                        Scale = scale,
                        InputImage = sourceImage,
                        AspectRatio = 1.0f
                    };
                }
                else
                {
                    transform = new CILanczosScaleTransform
                    {
                        Scale = scale,
                        Image = sourceImage,
                        AspectRatio = 1.0f
                    };
                }


```

Using the new InputImage seems to rotate correct! pushing out a new package :)

**Comment by jamesmontemagno** [comment] 2019-11-12 22:27
Or I hope that is it. Still validating.

**Comment by dhewitson** [comment] 2019-11-12 22:37
Classic Apple...

**Comment by jamesmontemagno** [comment] 2019-11-12 22:43
Looks like that wasn't it.

So a few workarounds that I have validated:

1. Save MetaData = false
2. Call GetStreamWithImageRotatedForExternalStorage, which will rotate it based on exif data (SaveMetaData must be true).

My only other assumption is that the UIImageView maybe changed how it renders items out.... not sure though.

**Comment by klogeaage** [comment] 2019-11-12 23:14
@jamesmontemagno: 

> It looks like the exif data is coming in just fine on the file, so if you using a library that reads the exif data it will be there.

Nope, that is part of the problem that no EXIF data is available with the file. I use the `ImageMetadataReader.ReadMetadata(filePath)` method from the` MetadataExtractor `2.2 package, and it cannot find location data or when the picture was digitized, both of which work fine pre iOS 13.2. 

So I'm sorry, but I don't think those of us that depend on EXIF data have a workaround.

**Comment by jamesmontemagno** [comment] 2019-11-12 23:29
It is obvious that Apple changed something in 13.2 and may actually revert it in 13.3... if someone has this beta could you please test your app with the library?

I didn't change how I save exif data to the file.... also I don't understand why it renders fine if I am not reading the exif data at all.... that makes no sense.

**Comment by jamesmontemagno** [comment] 2019-11-12 23:38
I have added a $100 bug bounty for a fix of this.

**Comment by rshah1803** [comment] 2019-11-13 09:37
After taking latest updated of 13.2.2 on iPhone 8 I found out two issues:
1)Image Rotation issue (Workaround is to use GetStreamWithImageRotatedForExternalStorage)
2)Exif data not saved 

Can any one please suggest how to get the Exif data

Thanks

**Comment by klogeaage** [comment] 2019-11-13 11:19
I have spent some time debugging this – unfortunately with no fix or workaround. But I have some additional information that might help someone else (@jamesmontemagno ):
1.	If you step through what goes on in `SaveImageWithMetadata` on iOS 12.x and iOS 13.2.x, it seems completely identical. All the same options and data as far as I can tell.
2.	But the image files written **_are_** different:
a.	 On iOS 12.x, the EXIF header and information is there and is recognized by EXIF readers, including on Windows (show file property details). 
b.	On iOS 13.2.x, the EXIF header is missing and instead, an ICC_PROFILE is added that I cannot see the code requests at all. It is not present on iOS 12.x.
3.	So to me, it seems like the call to the ` ImageIO` method `AddImageAndMetadata(cgImageFromJpeg, cgImageMetadata, destinationOptions)` on line 542 in `MediaPickerDelegate.cs` is behaving differently on the two platforms. 
4.	I have not been able to find any mentioning of this in Apple or Microsoft release documentation. There have been some changes to `ImageIO` in XCode 11.2 but nothing that seems to explain what I have observed. But it clearly seems like the plugin is innocent as it does what it has always done.

There is a new feature in iOS 13 that lets you specify for each image whether it should include location and other data when sharing. I tried playing with that, but it has no effect on this problem, which I think is good, so we can still hope this behavior is a bug and not a feature.

So to conclude, if you need EXIF data, the only workaround is to discourage your users from updating to iOS 13.2.x, which of course is not sustainable.

**Comment by pauldiston** [comment] 2019-11-13 14:02
Based on my limited testing, I believe this issue has introduced in 13.2.2 as an iPhone 7 running iOS 13.1.3 does not experience the same issue.

**Comment by klogeaage** [comment] 2019-11-13 14:21
Actually, the problem was there in iOS 13.2. Earlier versions seem OK.

**Comment by rshah1803** [comment] 2019-11-13 14:27
Exif issue is there in IOS 13 +
Rotation Issue is there in 13.2 +

**Comment by jamesmontemagno** [comment] 2019-11-13 20:35
So, it seems like in iOS 13.0 people are saying Exif data was no longer coming through. And then 13.2 was the orientation issue. My assumption here is they are linked together as the UIImage would load the Exif data.

**Comment by rshah1803** [comment] 2019-11-14 09:45
@jamesmontemagno  for me orientation works fine with IOS 13.1.3(iPhone 8) but not able to pull exif data

**Comment by supreettare** [comment] 2019-11-15 14:06
Hey guys, here is my observation. I am using Latest Stable version of 4.0.1.5 
on iOS 13.2 the images are rotating 180 degrees 
on iOS 12.4.3 we are all good. It's working as expected. 
I am using TakePhotoAsync 

Looks like this is indeed iOS 13.2 issue to me. 
Hope this helps someone.

**Comment by klogeaage** [comment] 2019-11-15 16:22
@jamesmontemagno what is the next step? Create a bug with Apple? Or is there another way of writing the image file that does not misbehave?

**Comment by klogeaage** [comment] 2019-11-19 08:58
iOS 13.2.3 is out with no fix - same issue prevails.

**Comment by MitchBomcanhao** [comment] 2019-11-19 09:10
on iOS 13.3 beta 2 the issue is still there.

**Comment by jamesmontemagno** [comment] 2019-11-19 21:57
Can confirm that 13.3 doesn't not fix it. I think it has to do with metadata somewhat. A bit confusing that if you say save metadata to false that it works.

**Comment by dinisvieira-xo** [comment] 2019-11-20 11:55
@jamesmontemagno It's also working for me if I set "SaveMetaData=false;" for both PickPhotoAsync and TakePhotoAsync.

Versions:
iOS version: 13.2.x
Media Plugin: 4.0.1.5
Xamarin Forms: 2.5.x

**Comment by mr5z** [comment] 2019-11-21 02:44
Hi,

Not a solution but to just add some info. It may helped if everyone who have issues with the image orientation also includes in which software, platform/OS they viewed the image.

Images in iOS are not actually rotated after it has been taken from camera, it just saves the exif orientation metadata for the client consumption. It was claimed that when the image is viewed on the default image app in Windows, it doesn't [honor the exif metadata](https://stackoverflow.com/q/10600613/2304737) and just draws the image thus producing incorrect results sometimes.

I have also reproduced the bug when I used this [exif reader tool](http://exif.regex.info/exif.cgi) to view the image. It display incorrectly on that site but displays correctly when viewed directly using Chrome for Mac.

**Comment by kdekok** [comment] 2019-11-21 15:42
I can confim having these issues, and i'm glad this thread proves i'm not the only one!

We don't call GetStream(), but just upload the raw file after
` var file = await CrossMedia.Current.TakePhotoAsync(options);`

When needed, we rotate it on the backend, depending on the EXIF data, which is missing for our users since iOS 13.2. I hope Apple will fix this soon, otherwise we'll have to give the workarounds a go but that would  require an app update unfortuantely...

**Comment by MatthewKapteyn** [comment] 2019-11-21 20:10
I think the $100 bounty should go to https://github.com/jamesmontemagno/MediaPlugin/issues/747#issuecomment-549250339

Used their code instead of the wacky manual copy-pasteover code in SaveImageWithMetadata and all is right in the world again. 

`internal static bool SaveImageWithMetadata(UIImage image, float quality, NSDictionary meta, string path, string pathExtension)
		{
            try
			{
				pathExtension = pathExtension.ToLowerInvariant();
				var finalQuality = quality;
				var imageData = pathExtension == "jpg" ? image.AsJPEG(finalQuality) : image.AsPNG();

				//continue to move down quality , rare instances
				while (imageData == null && finalQuality > 0)
				{
					finalQuality -= 0.05f;
					imageData = image.AsJPEG(finalQuality);
				}

				if (imageData == null)
					throw new NullReferenceException("Unable to convert image to jpeg, please ensure file exists or lower quality level");

                var saveSuccessful = false;

                // Copy over meta data
                using (var ciImage = CIImage.FromData(imageData))
                {
                    using (var newImageSource = ciImage.CreateBySettingProperties(meta))
                    {
                        using (var ciContext = new CIContext())
                        {
                            saveSuccessful = ciContext.WriteJpegRepresentation(newImageSource, NSUrl.FromFilename(path), CGColorSpace.CreateSrgb(), new NSDictionary(), out var error);
                        }
                    }
                }

                return saveSuccessful;
            }
			catch (Exception ex)
			{
				Console.WriteLine($"Unable to save image with metadata: {ex}");
			}

			return false;
		}`

**Comment by MatthewKapteyn** [comment] 2019-11-21 20:33
one word of caution is that I have no use for PNG in my app and have no idea if the settings in WritePngRepresentation are ideal.

**Comment by MatthewKapteyn** [comment] 2019-11-21 21:00
One last note while i'm running builds on a variety of devices. No issues with backwards compatibility going as far back as iOS 9.3.4.

**Comment by jamesmontemagno** [comment] 2019-11-21 21:02
Cools, I am putting in code that only applies this to iOS 13+ as that was the main impact. Thanks for testing it out and I will figure out the bounty stuff when tested out.

**Comment by ManbirSinghRakhra** [comment] 2019-11-21 21:14
@MatthewKapteyn Thanks very much for appreciating it. We need it very badly. I spent a long time to create a patch in my code. I am glad that you guys liked it.

I will update my project for Media Plugin

**Comment by jamesmontemagno** [comment] 2019-11-21 21:35
can try latest 4.4.7-beta

**Comment by klogeaage** [comment] 2019-11-22 09:15
Good work :-).
I think the new code in `SaveImageWithMetadataiOS13()` should be standard as it is simpler and more flexible. Otherwise we will likely also face the same problem in a year when iOS 14 comes out. But lets first see if it introduces other problems in the coming months.

**Comment by ClausElmann** [comment] 2019-11-22 11:11
Hi James

The beta introduces further dependencies, can I overcome this?

Severity	Code	Description	Project	File	Line	Suppression State
Error		Failed to add reference. The package 'Xam.Plugin.Media' tried to add a framework reference to 'System.Drawing.Common.dll' which was not found in the GAC. This is possibly a bug in the package. Please contact the package owners for assistance.
Error HRESULT E_FAIL has been returned from a call to a COM component.				


Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1605	Detected package downgrade: Plugin.Permissions from 5.0.0-beta to 3.0.0.12. Reference the package directly from the project to select a different version. 
 Mobile.Portable -> Xam.Plugin.Media 4.4.7-beta -> Plugin.Permissions (>= 5.0.0-beta) 
 Mobile.Portable -> Plugin.Permissions (>= 3.0.0.12)

**Comment by jamesmontemagno** [comment] 2019-11-22 17:44
So, you should use 5.0.0-beta of permisions plugin else you will run into issues. 

Make sure any other library you are using from me is using this version. so like geolocator or other stuff.

For System.Drawing.Common... oddd it shouldn't be there. Make sure you are using package refereneces: see: https://github.com/MvvmCross/MvvmCross/issues/3531

**Comment by jamesmontemagno** [comment] 2019-11-22 17:56
I'll push out 4.4.8, let me know if that helps.

**Comment by ClausElmann** [comment] 2019-11-23 15:24
Still some strange issue on nuget WS2019/Windows.

Severity	Code	Description	Project	File	Line	Suppression State
Error		Failed to add reference. The package 'Xam.Plugin.Geolocator' tried to add a framework reference to 'System.Drawing.Common.dll' which was not found in the GAC. This is possibly a bug in the package. Please contact the package owners for assistance.
Error HRESULT E_FAIL has been returned from a call to a COM component.				

On Mac - it works perfekt.

**Comment by RhomGit** [comment] 2019-11-23 22:18
Possibly related to: https://github.com/xamarin/xamarin-macios/issues/7249

**Comment by rshah1803** [comment] 2019-11-28 11:27
thanks @jamesmontemagno it fixed rotation and exif issue but still one minor issue.

In my app I am using TakephotoSync to click photo and then displaying it on page after photo is clicked, for displaying photos I have written code in OnAppearing() of the page, but after TakePhotoSync its not calling OnAppeatring(), is this something can you please check

Thanks,
Rohan

**Comment by jamesmontemagno** [comment] 2019-12-10 19:38
@ClausElmann you will need to convert to PackageReferences in your app. It is super simple to do.

**Comment by ClausElmann** [comment] 2019-12-10 19:54
@jamesmontemagno 
Thanks, just found  this post https://forums.xamarin.com/discussion/122700/how-to-convert-android-ios-projects-to-use-csproj-for-package-references

**Comment by vbmanuel2295** [comment] 2019-12-11 08:08
Hi @jamesmontemagno ,

After updating to 4.4.8, issue still exist on iOS 13.2.3 using PickPhotoAsync and SaveMetadata = false.

Can you or someone please let me know what's your config to make it work on iOS?

Thank you in advance

**Comment by rshah1803** [comment] 2019-12-19 10:47
@jamesmontemagno  when  can we get stable version with rotation and exif data fix please

Thanks
Rohan

**Comment by fjavaler** [comment] 2019-12-20 17:06
I am having this issue after upgrading to iOS 13.3.

**Comment by Ralpharoo** [comment] 2019-12-22 03:34
@jamesmontemagno FYI - Slightly off topic but related to the metadata conversation & issues in here. We need original metadata for the camera specs, saw the resulting images bloating (when selected from the gallery) and rotation issues. All while requesting the unedited `PhotoSize.Full`.

I have managed to get all existing metadata copied into the newly created image.  It would appear that `image.AsJPEG().Save(path, true);` is known to strip out the majority of the metadata. 

The stand in code to save the image with full original metadata, size etc. (negating the UIImage process) is as follows. This preserves meta and seemingly solves the rotation issues too for us;

```
// Instead, copy the image bytes and save the raw data
bool savedImage = false;
try
{
    IntPtr buf = CFAllocator.Malloc.Allocate(rep.Size);  // will be freed automatically when associated NSData is deallocated
    NSError err = null;
    System.nuint bytes = rep.GetBytes(buf, 0, (System.nuint)rep.Size, out err);

    Console.WriteLine(@"getBytes: {0}", bytes);
    if (err != null || bytes == 0)
    {
        // Are err and bytes == 0 redundant? Doc says 0 return means error occurred which presumably means NSError is returned?
        Console.WriteLine(@"error from getBytes: {0}", err);
    }
    else
    {
        var jpg = NSData.FromBytesNoCopy(buf, (nuint)rep.Size, true);
        jpg.Save(path, true);
        savedImage = true;
    }
}
catch (Exception ex)
{
    Console.WriteLine(ex.StackTrace);
}
```

Credit goes to Chris Markle here; [https://stackoverflow.com/questions/5173764/from-the-results-of-uiimagepickercontrollehow-how-do-i-get-jpeg-with-metadata-i](https://stackoverflow.com/questions/5173764/from-the-results-of-uiimagepickercontrollehow-how-do-i-get-jpeg-with-metadata-i)

Appreciate this should probably be done with the newer Photos SDK but I do not think the required API is available, namely; CGImageDestinationAddImageFromSource

Let me know if you have any questions.

**Closed** 2019-12-24 19:03 UTC
Labels: $100-bounty

**Comment by fjavaler** [comment] 2020-01-09 19:52
What type of object is "rep"?

**Comment by Alextorres950325** [comment] 2020-09-18 18:12
Again happens iOs in 13.7
