### ISSUE TITLE
On TakePhoto, Photo's orientation gets changed from Portrait to Landscape on Android Device

### ISSUE THREAD

**Issue by protokovich** [jamesmontemagno/MediaPlugin#285] opened 2017-06-28 11:14 UTC
## Bug Information

Version Number of Plugin: 3.0.0.66-alpha
Device Tested On: Sony Xperia Z2 (Android 6.0.1)
Simulator Tested On:
Version of VS: 2017: 15.2(26430.14)
Version of Xamarin: Xamarin.Forms: 2.3.5.255-pre
Versions of other things you are using: Xamarin: 4.5.0.486, Xamarin.Android: 7.3.1.12, Xamarin.iOS: 10.10.0.37
Target Framework: Android 7.1

### Steps to reproduce the Behavior
1. Take a portrait photo from the camera
2. The orientation gets changed to landscape

### Expected Behavior
Image width should be < then height.

### Actual Behavior
1. The photo appears as landscape
2. Image width > height

### Code snippet
this is my class for working with Media Plugin
```
public static class ImageHelper
    {
        public static async Task<MediaFile> TakePhoto(int maxWidthHeight = 0, int quality = 100)
        {

            try
            {
                await CrossMedia.Current.Initialize();
            }
            catch (Exception e)
            {
                App.Dbg(e);
                throw new Exception("Ошибка инициализации: " + e.Message);
            }
            
            //var file = await CrossMedia.Current.PickPhotoAsync();

            if (!CrossMedia.Current.IsCameraAvailable) {
                App.Dbg("!!! Камера недоступна !!!");
                throw new Exception("Камера недоступна !!");
            }
                       

            if (!CrossMedia.Current.IsTakePhotoSupported) {
                App.Dbg("!!! Получение фото недоступно !!");
                throw new Exception("Получение фото недоступно !!");                
            }

            MediaFile file = null;
            
            try
            {
                file = await CrossMedia.Current.TakePhotoAsync(new Plugin.Media.Abstractions.StoreCameraMediaOptions
                {
                    Directory = "Sample",
                    Name = "test.jpg",
                    RotateImage = true,
                    DefaultCamera = CameraDevice.Rear,
                    //SaveToAlbum = true
                    PhotoSize = maxWidthHeight == 0 ? PhotoSize.Full : PhotoSize.MaxWidthHeight,
                    
                    MaxWidthHeight = maxWidthHeight,
                    CompressionQuality = quality,
                });
            }
            catch (Exception e) {
                App.Dbg($"TakePhotoAsync Exception: {e.Message}");
                throw;
            }
            return file;
        }

        public static async Task<MediaFile> PickPhoto(int maxWidthHeight = 0, int quality = 100)
        {

            try
            {
                await CrossMedia.Current.Initialize();
            }
            catch (Exception e)
            {
                App.Dbg(e);
                throw new Exception("Ошибка инициализации: " + e.Message);
            }

            //var file = await CrossMedia.Current.PickPhotoAsync();

            if (!CrossMedia.Current.IsPickPhotoSupported)
            {
                App.Dbg("!!! Получение фото недоступно !!");
                throw new Exception("Получение фото недоступно !!");
            }

            MediaFile file = null;

            try
            {
                file = await CrossMedia.Current.PickPhotoAsync(new PickMediaOptions()
                    {
                        PhotoSize = maxWidthHeight == 0 ? PhotoSize.Full : PhotoSize.MaxWidthHeight,

                        MaxWidthHeight = maxWidthHeight,
                        CompressionQuality = quality,
                    }
                );
            }
            catch (Exception e)
            {
                App.Dbg($"TakePhotoAsync Exception: {e.Message}");
                throw;
            }
            return file;
        }
    }
```
this is my helper for streams:
```
public static class StreamHelper
    {
        public static async Task<byte[]> GetBytes(this Stream stream)
        {
            stream.Seek(0, SeekOrigin.Begin);

            MemoryStream memStream = new MemoryStream();
            await stream.CopyToAsync(memStream);
            memStream.Seek(0, SeekOrigin.Begin);

            byte[] bytes = memStream.ToArray();
            memStream.Dispose();

            return bytes;
        }
    }

```
this is my snippet:
```
file = await ImageHelper.PickPhoto(maxWidthHeight: 1600, quality: 70);
Stream stream = file.GetStream();
byte[] imageData = await stream.GetBytes();
```

then i use ImageEdit plugin [https://github.com/muak/Xamarin.Plugin.ImageEdit] :
`var image = await CrossImageEdit.Current.CreateImageAsync(imageData)`

and image.Widrh > image.Height

if you don't like ImageEdit, you can use custom native android function:
```
public Size GetImageSizeFromBytes(byte[] bytes)
        {
            var options = new BitmapFactory.Options
            {
                InJustDecodeBounds = true
            };

            BitmapFactory.DecodeByteArray(bytes, 0, bytes.Length, options);
            return new Size((double)options.OutWidth, (double)options.OutHeight);
        }
```
same result

p.s. sorry my english )

**Comment by protokovich** [comment] 2017-06-28 11:32
In older versions there was a bug:
https://github.com/jamesmontemagno/MediaPlugin/issues/225

it was fixed in 2.7+

but in current version of plugin, if i run TakePhotoAsync, wait ~8 sec, then take portarait photo - orientation is correct.
in older version, if i run TakePhotoAsync, wait < ~8 sec, then take  photo - i had solid grey 1x1 image.

in current version this "solid grey" bug fixed, But now the same "wait 8 sec" behavior with orientation

**Comment by jamesmontemagno** [comment] 2017-06-28 14:51
I am not sure if you are saying the bug if fixed or not fixed?

**Comment by protokovich** [comment] 2017-06-28 15:15
not fixed. 
Received in portrait mode photo, will be in portrait orientation, if I do not wait ~8 sec from the moment the camera was started.

There used to be a similar bug when the photo came in size 1x1, if not wait about 8 seconds. But it was fixed in 2.7+ version.

**Comment by jamesmontemagno** [comment] 2017-06-28 15:23
What version of the plugin are you using? you say 3.x, but then you said it was fixed in 2.7+...

Please create a reproduction sample for me to try on my devices.

**Comment by jamesmontemagno** [comment] 2017-06-28 15:31
Is this happening when it is set to full or max height..
you need to give me a better sample to try.

**Comment by protokovich** [comment] 2017-06-28 17:47
plugin version 3.0.0.66-alpha. see Bug Information :)
1. run TakePhotoAsync (with the parameters described above)
2. opening camera...
3. set portrait orientation of device
4. press take photo button
5. resulting photo in landscape orientation
![screenshot_20170628-204345](https://user-images.githubusercontent.com/11036196/27652031-e7a88698-5c42-11e7-80e2-4ba1d0362a80.png)

**Comment by protokovich** [comment] 2017-06-28 17:49
If you wait about 8 seconds between 3 and 4 steps, the resulting photo will be in normal portrait mode

**Comment by jamesmontemagno** [comment] 2017-06-28 18:11
How are you loading the image in a standard image control? You seem to be using other plugins. Can you create a sample that ONLY uses the media plugin that you can share with me so I can reproduce with the exact setting that are causing it. I know you are providing a lot of information, but it just doesn't really help without the exact reproduction without interaction with other plugins.

**Comment by jamesmontemagno** [comment] 2017-06-28 18:13
The plugin auto rotates and resizes the image. There is a flag you can pass it so it skips any rotation at all if you are using something like FFImageloader as it reads the exif data.

**Comment by protokovich** [comment] 2017-06-28 22:40
1. create empty xamarin.forms shared project
2. android project - target framework = android 7.1
3. update all nugets to pre-releases
4. install xam.plugin.media 3.0.0.66-alpha
5. add in MainActivity:
```
public override void OnRequestPermissionsResult(int requestCode, string[] permissions, Permission[] grantResults)
{
    PermissionsImplementation.Current.OnRequestPermissionsResult(requestCode, permissions, grantResults);
}

```
6. set content of MainPage:
```
<ScrollView>
    <StackLayout Spacing="10" Padding="10">
        <Button x:Name="takePhoto" Text="Take Photo"/>
        <Image x:Name="image"/>
    </StackLayout>
</ScrollView>
```
7. in MainPage.xaml.cs :
```
public partial class MainPage : ContentPage
{
    public MainPage()
	{
		InitializeComponent();

	    takePhoto.Clicked += async (sender, args) =>
	    {

	        if (!CrossMedia.Current.IsCameraAvailable || !CrossMedia.Current.IsTakePhotoSupported)
	        {
	            DisplayAlert("No Camera", ":( No camera avaialble.", "OK");
	            return;
	        }

	        var file = await CrossMedia.Current.TakePhotoAsync(new Plugin.Media.Abstractions.StoreCameraMediaOptions
	        {
	            Directory = "Sample",
	            Name = "test.jpg",

	            RotateImage = true,
	            DefaultCamera = CameraDevice.Rear,
	            //SaveToAlbum = true
	            PhotoSize = PhotoSize.MaxWidthHeight,

	            MaxWidthHeight = 1600,
	            CompressionQuality = 70,
            });

	        if (file == null)
	            return;

	        //DisplayAlert("File Location", file.Path, "OK");

	        image.Source = ImageSource.FromStream(() =>
	        {
	            var stream = file.GetStream();
	            file.Dispose();
	            return stream;
	        });
	    };
    }
}

```

then run app, "take photo",  set portrait orientation of device, press button, and image on MainPage in landscape mode. if you wait about 8 sec before pressing capture button in camera app - rotation is ok

test project: https://www.dropbox.com/s/1ts7y9gklz44264/TestMediaPluginRotation.ZIP?dl=0

**Comment by protokovich** [comment] 2017-06-28 23:16
That's why, for example, Viber uses custom own "camera view" to access the native camera methods directly, bypassing vendor camera apps :)

**Comment by jamesmontemagno** [comment] 2017-06-29 01:29
Thanks for the sample. testing it out now on my Nexus 6 (running 5.1.1) getting a few more test device soon.

You are literally saying though that based on how long the camera is open determines if the bug exists or not?

**Comment by protokovich** [comment] 2017-06-29 10:19
yes :)

**Comment by jamesmontemagno** [comment] 2017-06-29 16:52
I tested it several time on my Nexus 6 and can't reproduce or on emulators. I purchased 2 additional devices for testing, however it seems like it is with the device and camera specific and not the library as waiting indicates that something is going on with the camera.

**Comment by protokovich** [comment] 2017-06-30 10:33
Most likely you are right

**Comment by jamesmontemagno** [comment] 2017-06-30 17:35
I will validate on a few others, but you can try to install some other camera apps from the app store and try.

**Comment by jamesmontemagno** [comment] 2017-07-01 00:03
I tested it on a BLU device running 4.4 and Alcatel running 7.0 as well as my Nexus 6 running 5.1.1 and can't reproduce.

**Closed by jamesmontemagno** 2017-07-01 00:03 UTC

**Comment by antontereshko** [comment] 2018-03-12 12:04
I can repeat this bug on Samsung S8.

**Comment by Bejasc** [comment] 2018-03-20 03:18
I can repeat this bug, but seemingly on iOS only. It also seems to only happen to photos picked from image gallery, not photos taken using camera. 
iPad Pro, iOS 11.2 , Cross Media v 3.1.3

**Comment by lobbo232** [comment] 2018-07-06 09:49
I am able to recreate this every single time i take a photo on an iPad Air 2 and iPhone 6 running iOS 11.4 on the front and rear cameras.  Every test resulted in the image being rotated 90 degrees clockwise. The image is just being set to a standard xamarin.forms Image element

Also tested with:
Wileyfox Swift (Android 7.1.2) - works OK
Wileyfox Swift 2 (Android 8.1.0) - works OK

I have tried with setting the RotateImage property to false and true.

`var photo = await CrossMedia.Current.TakePhotoAsync(new StoreCameraMediaOptions
{
    PhotoSize = PhotoSize.Large,
    AllowCropping = true,
    SaveToAlbum = false
});`

**Comment by qwertylolman** [comment] 2018-07-18 13:59
we have the same bug on v3.2.1, any iphone with any ios version

**Comment by James-A-White** [comment] 2018-08-06 13:06
Orientation works fine for me as long as I set AllowCropping = false. As soon as I set AllowCropping = true, the image is rotated.

**Comment by Microdec** [comment] 2018-11-26 09:04
After upgrading from quite an old version to the current version (4.0.1.5) am now also experiencing this for iOS only. Any word on whether this is going to be fixed?

**Comment by luiznegrinidatum** [comment] 2019-01-02 17:44
Same for iOS devices here.

**Comment by upskydownshoes** [comment] 2019-01-30 15:52
Yup. Me too. "Orientation works fine for me as long as I set AllowCropping = false. As soon as I set AllowCropping = true, the image is rotated."

**Comment by seddik** [comment] 2019-02-12 16:19
As for me it happens on my iphone 6S ios 12.1 and Galaxy S7

**Comment by dktechindia** [comment] 2019-02-13 03:27
Any update on iOS device? I am using latest version of the plugin and its still rotating the image. Even if I choose from the gallery then also it rotates.

I tried with almost all combinations like setting Rotate to false and Cropping to true and vice versa and setting both to true, None worked.

**Comment by seddik** [comment] 2019-02-18 16:06
@jamesmontemagno for android version I've tested with several devices all is good, but not with any of Galaxy S5 / S7 / S8+
so I think the problem is with the galaxy devices !

**Comment by sandlergiovanni** [comment] 2019-02-21 15:42
Same error: iPhone 6S iOS 12.1.4

**Comment by sandlergiovanni** [comment] 2019-05-17 16:03
> Same error: iPhone 6S iOS 12.1.4

Solved:
`        private void TakePhotoCommandExecute()
        {
            if (this.IsBusy)
                return;
            this.IsBusy = true;
            this.fileIndex = 0;
            this.Files[this.fileIndex] = null;
            Device.BeginInvokeOnMainThread(async() => {
                var active = await CrossMedia.Current.Initialize();
                if (!active || !CrossMedia.Current.IsCameraAvailable || !CrossMedia.Current.IsTakePhotoSupported)
                    await Application.Current.MainPage.DisplayAlert("Sem câmera!", "Não há câmera disponível.", "Ok");
                else
                {
                    var file = await CrossMedia.Current.TakePhotoAsync(new StoreCameraMediaOptions
                    {
                        //AllowCropping = true,
                        CompressionQuality = 70,
                        DefaultCamera = CameraDevice.Rear,
                        Directory = "MyUploads",
                        ModalPresentationStyle = MediaPickerModalPresentationStyle.OverFullScreen,
                        PhotoSize = PhotoSize.Medium,
                        RotateImage = true, // Important
                        SaveToAlbum = true
                    });
                    if (file != null)
                        this.SetupFileArrayContent(file);
                }
                this.IsBusy = false;
            });
        }

        protected void SetupFileArrayContent(MediaFile file)
        {
            if (file != null)
            {
                var currentSize = file.GetStream().Length;
                var buffer = new byte[16 * 1024];
                using (var memStream = new System.IO.MemoryStream())
                {
                    int read = 0;
                    //var readStream = file.GetStream();
                    var readStream = file.GetStreamWithImageRotatedForExternalStorage(); // Important
                    while ((read = readStream.Read(buffer, 0, buffer.Length)) > 0)
                        memStream.Write(buffer, 0, read);
                    this.Files[this.fileIndex] = memStream.ToArray();
                    readStream.Dispose();
                    readStream = null;
                }
                file.Dispose();
            }
        }`
