### ISSUE TITLE
iOS Not working on latest Xamarin Forms

### ISSUE THREAD

**Issue by Bobisback** [jamesmontemagno/MediaPlugin#216] opened 2017-04-05 13:30 UTC
## Bug 

Version Number of Xamarin Forms: 2.3.4.221-pre6 
Version Number of Plugin: 2.6.3.8-beta
Device Tested On: iPhone 6 Plus 10.2.1
Simulator Tested On: iPhone 6 10.2

### Expected Behavior
When I click my Button to take a photo I expect the photo controller to be displayed so I can take a picture.
When I Click my button to choose a photo I expect the photo library to open to choose my photo.

### Actual Behavior
Nothing Happens, no logs, no xamarin logs no exceptions. I cannot figure out what the issues is with it. It is not a permissions thing since it is asking for permission correctly. After I grant permission nothing happens. I even walked through the code and everything is running just fine with no issues. 

### Steps to reproduce the Behavior
Create a project update to latest xamarin forms, install the media plugin, and add permissions. Try to take a picture.

### Notes: 
If you downgrade to xamarin 2.3.3.193 it works fine. Not sure if it is an xamarin issue or not.

**Comment by eopeter** [comment] 2017-04-06 01:21
Having the same issue after upgrading to Xamarin Forms 2.3.4

**Comment by jamesmontemagno** [comment] 2017-04-06 01:41
Unable to repo on my test project.

Please share a small repo project so I can reproduce.

**Comment by eopeter** [comment] 2017-04-06 02:17
I was able to replicate it again on a brand new project using Xamarin.Forms 2.3.4

https://github.com/eopeter/MediaTest

Thanks

**Comment by jamesmontemagno** [comment] 2017-04-06 03:28
what if you change this: MainPage = new testPage();

to MainPage = new NavigationPage(new testPage());

**Comment by eopeter** [comment] 2017-04-06 03:36
Still does not work after changing how I set the MainPage using NavigationPage. If I try to pick a photo or start the camera, nothing happens; I try again and then crashes with following error: "Only one operation can be active at at time". Tried on Simulator and same result

**Comment by Bobisback** [comment] 2017-04-06 03:36
Ya I get the same as above.

**Comment by jamesmontemagno** [comment] 2017-04-06 11:16
Duplicate of: https://github.com/jamesmontemagno/MediaPlugin/issues/186

**Closed by jamesmontemagno** 2017-04-06 11:16 UTC
Labels: need-more-info
