### ISSUE TITLE
Failed to add reference. The package 'Xam.Plugin.Media' tried to add a framework reference to 'System.Drawing.Common.dll' which was not found in the GAC.

### ISSUE THREAD

**Issue by OPunktSchmidt** [jamesmontemagno/MediaPlugin#756] opened 2019-10-14 12:29 UTC
I get this error when i try to add the latest version of this nuget package to my Xamarin.Forms project. 

```
Failed to add reference. The package 'Xam.Plugin.Media' tried to add a framework reference to 'System.Drawing.Common.dll' which was not found in the GAC. This is possibly a bug in the package. Please contact the package owners for assistance.
Reference unavailable.					

```

Does anyone have any idea what the cause is and how to solve it?

**Version Number of Plugin i try to install: 4.4.3 - beta
Version Number of Plugin i able to install: 4.3.0 - beta**
Version of VS: 2019 16.3.4
Version of Xamarin: 4.2.0.848062

**Comment by jamesmontemagno** [comment] 2019-10-14 20:30
I can't reproduce here, but I did file an issue with the packaging library I use https://github.com/onovotny/MSBuildSdkExtras/issues/192 i see it in the nuget, but i just did file-> new and it was fine when i added it. are you using PackageReferences or do you have a packages.config file in your project?

**Comment by OPunktSchmidt** [comment] 2019-10-15 08:05
I use PackageReferences

**Comment by WillAutioItrax** [comment] 2019-10-15 21:28
FWIW, I am getting the same message. Droid and UWP work fine but iOS does not update to 4.4.3-beta from 4.3.1-beta
Version of VS: 2019 16.3.5
Version of Xamarin: 4.3.0.277

**Comment by jamesmontemagno** [comment] 2019-10-16 03:45
What if you uninstall it completely and re-add it?

**Comment by OPunktSchmidt** [comment] 2019-10-16 06:44
Uninstalling and adding new does not help

**Comment by WillAutioItrax** [comment] 2019-10-16 16:33
I noticed a 4.4.4-beta this morning, so I uninstalled the version for iOS and tried to install 4.4.4-beta. Instead of installing, I get the message:
Error		Failed to add reference. The package 'Xam.Plugin.Media' tried to add a framework reference to 'System.Drawing.Common.dll' which was not found in the GAC. This is possibly a bug in the package. Please contact the package owners for assistance.
Reference unavailable.

**Comment by jamesmontemagno** [comment] 2019-10-17 05:09
Linking to https://github.com/martijn00/XamarinMediaManager/issues/558#issuecomment-543004654 for ref. I need to figure out how to remove it from the nuget.

**Comment by jamesmontemagno** [comment] 2019-10-17 05:42
You can download this one and give it a go. I had to build the library in VS 2017. Investigating still. 
[Xam.Plugin.Media.4.4.4-beta.zip](https://github.com/jamesmontemagno/MediaPlugin/files/3737546/Xam.Plugin.Media.4.4.4-beta.zip)

**Comment by jamesmontemagno** [comment] 2019-10-17 06:01
When you go to:
`C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\ReferenceAssemblies\Microsoft\Framework\Xamarin.iOS\v1.0\Facades` does System.Drawing.Common.dll exist?

**Comment by jamesmontemagno** [comment] 2019-10-17 06:25
4.4.5-beta will also be built against 2017 to have the fix in it.

**Comment by WillAutioItrax** [comment] 2019-10-17 16:31
Woo hoo - works for me too. Thanks!

**Comment by jamesmontemagno** [comment] 2019-10-17 16:48
I opened an issue, but for now will continue to build on older versions as I don't need iOS 13 features specifically. Working on the team to resolve it though

**Comment by jamesmontemagno** [comment] 2019-10-17 19:38
Figure out the other issue with 2019 now, closing.

**Closed by jamesmontemagno** 2019-10-17 19:38 UTC

**Comment by GregWoods** [comment] 2020-01-31 16:49
This error has reappearred.
4.4.5 is Ok, 4.4.6 and 4.4.10 (and I presume the ones in-between) have the error again:

Failed to add reference. The package 'Xam.Plugin.Media' tried to add a framework reference to 'System.Drawing.Common.dll' which was not found in the GAC. This is possibly a bug in the package. Please contact the package owners for assistance.
Unspecified error (Exception from HRESULT: 0x80004005 (E_FAIL))

**Comment by thedee** [comment] 2020-02-05 22:19
I also get the error in  4.4.10-beta.

Failed to add reference. The package 'Xam.Plugin.Media' tried to add a framework reference to 'System.Drawing.Common.dll' which was not found in the GAC. This is possibly a bug in the package. Please contact the package owners for assistance.
Error HRESULT E_FAIL has been returned from a call to a COM component.

**Comment by gaelian** [comment] 2020-03-26 02:45
I'm getting this error when trying to install either 4.4.10-beta or 5.0.0-beta.

I'm using VS Professional 2019, I do see `System.Drawing.Common.dll` at `C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\Common7\IDE\ReferenceAssemblies\Microsoft\Framework\Xamarin.iOS\v1.0\Facades` if that helps.
